[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:xvfb]
command=Xvfb :99 -screen 0 1280x800x24 -ac +extension GLX +render -noreset
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:w3cos]
command=/usr/bin/w3cos-showcase
environment=DISPLAY=":99",WINIT_UNIX_BACKEND="x11"
autorestart=true
startretries=5
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:x11vnc]
command=x11vnc -display :99 -forever -shared -nopw -rfbport 5900 -xkb -noxrecord -noxfixes -noxdamage
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
command=websockify --web=/usr/share/novnc %(ENV_PORT)s localhost:5900
environment=PORT="7860"
autorestart=true
startsecs=4
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
