use crate::css_parser::Stylesheet;
use crate::parser::{AppTree, Node, NodeKind, SignalDecl, StyleDecl};
use crate::style_matcher;
#[allow(unused_imports)]
use anyhow::Context;
use anyhow::Result;

/// Generate a complete Rust main.rs that builds and runs a W3C OS application.
pub fn generate(tree: &AppTree, stylesheet: &Stylesheet) -> Result<String> {
    let is_reactive = !tree.signals.is_empty();
    let signal_names: Vec<&str> = tree.signals.iter().map(|s| s.name.as_str()).collect();
    let component_code = gen_node(&tree.root, 0, &signal_names, stylesheet);

    if is_reactive {
        let signal_inits = gen_signal_inits(&tree.signals);
        Ok(format!(
            r#"//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{{Component, EventAction, Style}};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {{
    w3cos_runtime::run_app(build_ui).expect("W3C OS app crashed");
}}

fn build_ui() -> Component {{
{signal_inits}
{component_code}
}}
"#
        ))
    } else {
        Ok(format!(
            r#"//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{{Component, Style}};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {{
    w3cos_runtime::run_app(build_ui).expect("W3C OS app crashed");
}}

fn build_ui() -> Component {{
{component_code}
}}
"#
        ))
    }
}

fn gen_signal_inits(signals: &[SignalDecl]) -> String {
    signals
        .iter()
        .enumerate()
        .map(|(i, sig)| {
            format!(
                "    let _ = w3cos_runtime::state::create_signal({initial});\n    let {name} = w3cos_runtime::state::get_signal({i});",
                initial = sig.initial,
                name = sig.name,
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Generate a Cargo.toml for the compiled application.
pub fn generate_cargo_toml(_output_dir: &std::path::Path) -> Result<String> {
    let workspace_root = find_workspace_root()?;
    let runtime_path = workspace_root.join("crates/w3cos-runtime");
    let std_path = workspace_root.join("crates/w3cos-std");

    Ok(format!(
        r#"[package]
name = "w3cos-app"
version = "0.1.0"
edition = "2024"

[dependencies]
w3cos-runtime = {{ path = "{runtime}" }}
w3cos-std = {{ path = "{std_}" }}
"#,
        runtime = runtime_path.display(),
        std_ = std_path.display(),
    ))
}

fn find_workspace_root() -> Result<std::path::PathBuf> {
    let exe = std::env::current_exe().unwrap_or_else(|_| std::env::current_dir().unwrap());
    let mut dir = exe.parent().unwrap().to_path_buf();

    // Walk up from the executable location
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    // Fallback: walk up from current working directory
    let mut dir = std::env::current_dir()?;
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    anyhow::bail!(
        "Could not find w3cos workspace root. Run from within the w3cos project directory."
    )
}

fn gen_node(node: &Node, depth: usize, signal_names: &[&str], stylesheet: &Stylesheet) -> String {
    let indent = "    ".repeat(depth + 1);
    let resolved = style_matcher::resolve_style(node, stylesheet);
    let style_code = gen_style(&resolved, depth + 1);

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            let text_expr = gen_text_expr(text, signal_names);
            format!("{indent}Component::text({text_expr}, {style_code})")
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                format!("{indent}Component::button_with_click({lbl:?}, {style_code}, {action})")
            } else {
                format!("{indent}Component::button({lbl:?}, {style_code})")
            }
        }
        NodeKind::Image(src) => {
            let src_val = node.src.as_deref().unwrap_or(src.as_str());
            format!("{indent}Component::image({src_val:?}, {style_code})")
        }
        NodeKind::TextInput => {
            let placeholder = node.placeholder.as_deref().unwrap_or("Enter text");
            format!("{indent}Component::text_input(\"\", {placeholder:?}, {style_code})")
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let constructor = match &node.kind {
                NodeKind::Column => "Component::column",
                NodeKind::Row => "Component::row",
                NodeKind::Box => "Component::boxed",
                _ => unreachable!(),
            };
            let children_code = if node.children.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = node
                    .children
                    .iter()
                    .map(|c| gen_node(c, depth + 2, signal_names, stylesheet))
                    .collect();
                format!("vec![\n{},\n{indent}]", items.join(",\n"))
            };
            format!("{indent}{constructor}({style_code}, {children_code})")
        }
    }
}

fn gen_text_expr(text: &str, signal_names: &[&str]) -> String {
    if !text.contains('{') {
        return format!("{text:?}");
    }
    // Check for {signal_name} interpolation
    for (i, name) in signal_names.iter().enumerate() {
        let placeholder = format!("{{{name}}}");
        if text == placeholder {
            return format!("w3cos_runtime::state::get_signal({i}).to_string()");
        }
        if text.contains(&placeholder) {
            return format!(
                "{text:?}.replace(\"{placeholder}\", &w3cos_runtime::state::get_signal({i}).to_string())"
            );
        }
    }
    format!("{text:?}")
}

fn gen_event_action(action_str: &str, signal_names: &[&str]) -> String {
    let parts: Vec<&str> = action_str.split(':').collect();
    if !parts.is_empty() && parts[0].trim() == "notify" {
        if parts.len() < 3 {
            return "EventAction::None".to_string();
        }
        let title = parts[1].trim();
        let body = parts[2..].join(":");
        return format!(
            "EventAction::Notify({:?}.to_string(), {:?}.to_string())",
            title, body
        );
    }

    if parts.len() < 2 {
        return "EventAction::None".to_string();
    }

    let action_type = parts[0].trim();
    let signal_name = parts[1].trim();
    let signal_id = signal_names
        .iter()
        .position(|&n| n == signal_name)
        .unwrap_or(0);

    match action_type {
        "increment" => format!("EventAction::Increment({signal_id})"),
        "decrement" => format!("EventAction::Decrement({signal_id})"),
        "toggle" => format!("EventAction::Toggle({signal_id})"),
        "set" => {
            let value = parts
                .get(2)
                .and_then(|v| v.trim().parse::<i64>().ok())
                .unwrap_or(0);
            format!("EventAction::Set({signal_id}, {value})")
        }
        _ => "EventAction::None".to_string(),
    }
}

fn gen_style(s: &StyleDecl, depth: usize) -> String {
    let indent = "    ".repeat(depth);
    let mut fields = Vec::new();

    if let Some(gap) = s.gap {
        fields.push(format!("gap: {gap}_f32"));
    }
    if let Some(p) = s.padding {
        fields.push(format!("padding: Edges::all({p}_f32)"));
    }
    if let Some(fs) = s.font_size {
        fields.push(format!("font_size: {fs}_f32"));
    }
    if let Some(fw) = s.font_weight {
        fields.push(format!("font_weight: {fw}"));
    }
    if let Some(ref c) = s.color {
        fields.push(format!("color: Color::from_hex({c:?})"));
    }
    if let Some(ref bg) = s.background {
        fields.push(format!("background: Color::from_hex({bg:?})"));
    }
    if let Some(br) = s.border_radius {
        fields.push(format!("border_radius: {br}_f32"));
    }
    if let Some(bw) = s.border_width {
        fields.push(format!("border_width: {bw}_f32"));
    }
    if let Some(ref bc) = s.border_color {
        fields.push(format!("border_color: Color::from_hex({bc:?})"));
    }
    if let Some(ref ai) = s.align_items {
        let variant = match ai.as_str() {
            "center" => "AlignItems::Center",
            "flex-start" | "flexStart" => "AlignItems::FlexStart",
            "flex-end" | "flexEnd" => "AlignItems::FlexEnd",
            "baseline" => "AlignItems::Baseline",
            _ => "AlignItems::Stretch",
        };
        fields.push(format!("align_items: {variant}"));
    }
    if let Some(ref jc) = s.justify_content {
        let variant = match jc.as_str() {
            "center" => "JustifyContent::Center",
            "flex-end" | "flexEnd" => "JustifyContent::FlexEnd",
            "space-between" | "spaceBetween" => "JustifyContent::SpaceBetween",
            "space-around" | "spaceAround" => "JustifyContent::SpaceAround",
            "space-evenly" | "spaceEvenly" => "JustifyContent::SpaceEvenly",
            _ => "JustifyContent::FlexStart",
        };
        fields.push(format!("justify_content: {variant}"));
    }
    if let Some(ref w) = s.width {
        fields.push(format!("width: {}", gen_dimension(w)));
    }
    if let Some(ref h) = s.height {
        fields.push(format!("height: {}", gen_dimension(h)));
    }
    if let Some(fg) = s.flex_grow {
        fields.push(format!("flex_grow: {fg}_f32"));
    }
    if let Some(ref d) = s.display {
        let variant = match d.as_str() {
            "block" => "Display::Block",
            "grid" => "Display::Grid",
            "inline" => "Display::Inline",
            "inline-block" => "Display::InlineBlock",
            "none" => "Display::None",
            _ => "Display::Flex",
        };
        fields.push(format!("display: {variant}"));
    }
    if let Some(ref t) = s.top {
        fields.push(format!("top: {}", gen_dimension(t)));
    }
    if let Some(ref r) = s.right {
        fields.push(format!("right: {}", gen_dimension(r)));
    }
    if let Some(ref b) = s.bottom {
        fields.push(format!("bottom: {}", gen_dimension(b)));
    }
    if let Some(ref l) = s.left {
        fields.push(format!("left: {}", gen_dimension(l)));
    }
    if let Some(zi) = s.z_index {
        fields.push(format!("z_index: {zi}"));
    }
    if let Some(ref p) = s.position {
        let variant = match p.as_str() {
            "absolute" => "Position::Absolute",
            "fixed" => "Position::Fixed",
            "sticky" => "Position::Sticky",
            _ => "Position::Relative",
        };
        fields.push(format!("position: {variant}"));
    }
    if let Some(ref ov) = s.overflow {
        let variant = match ov.as_str() {
            "hidden" => "Overflow::Hidden",
            "scroll" => "Overflow::Scroll",
            "auto" => "Overflow::Auto",
            _ => "Overflow::Visible",
        };
        fields.push(format!("overflow: {variant}"));
    }

    if fields.is_empty() {
        "Style::default()".to_string()
    } else {
        let joined = fields.join(&format!(",\n{indent}    "));
        format!("Style {{\n{indent}    {joined},\n{indent}    ..Style::default()\n{indent}}}")
    }
}

fn gen_dimension(val: &str) -> String {
    let val = val.trim();
    let suffixes: &[(&str, &str)] = &[
        ("%", "Dimension::Percent"),
        ("px", "Dimension::Px"),
        ("rem", "Dimension::Rem"),
        ("em", "Dimension::Em"),
        ("vw", "Dimension::Vw"),
        ("vh", "Dimension::Vh"),
    ];
    for &(suffix, variant) in suffixes {
        if let Some(num_str) = val.strip_suffix(suffix)
            && let Ok(n) = num_str.trim().parse::<f32>()
        {
            return format!("{variant}({n}_f32)");
        }
    }
    if val == "auto" {
        return "Dimension::Auto".to_string();
    }
    if let Ok(n) = val.parse::<f32>() {
        return format!("Dimension::Px({n}_f32)");
    }
    "Dimension::Auto".to_string()
}

// ---------------------------------------------------------------------------
// DOM codegen backend — generates document.createElement / appendChild calls
// ---------------------------------------------------------------------------

/// Generate Rust code that builds a DOM tree using w3cos_runtime::dom APIs.
pub fn generate_dom(tree: &AppTree) -> Result<String> {
    let is_reactive = !tree.signals.is_empty();
    let signal_names: Vec<&str> = tree.signals.iter().map(|s| s.name.as_str()).collect();
    let mut body = String::new();

    if is_reactive {
        for (i, sig) in tree.signals.iter().enumerate() {
            body.push_str(&format!(
                "    let _ = w3cos_runtime::state::create_signal({});\n    let {} = w3cos_runtime::state::get_signal({});\n",
                sig.initial, sig.name, i
            ));
        }
        body.push('\n');
    }

    let mut counter = 0;
    let root_var = gen_dom_node(&tree.root, &mut body, &mut counter, 1, &signal_names);
    body.push_str(&format!("\n    let body = w3cos_runtime::dom::body_id();\n"));
    body.push_str(&format!(
        "    w3cos_runtime::dom::append_child(body, {root_var});\n"
    ));

    let imports = if is_reactive {
        "use w3cos_std::EventAction;\n"
    } else {
        ""
    };

    Ok(format!(
        r#"//! Auto-generated by w3cos compiler — do not edit (DOM mode).
{imports}
fn main() {{
    w3cos_runtime::run_app_dom(setup).expect("W3C OS app crashed");
}}

fn setup() {{
{body}}}
"#
    ))
}

fn gen_dom_node(
    node: &Node,
    out: &mut String,
    counter: &mut usize,
    depth: usize,
    signal_names: &[&str],
) -> String {
    let indent = "    ".repeat(depth);
    let var = format!("n{}", *counter);
    *counter += 1;

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            let text_expr = gen_text_expr(text, signal_names);
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_text_node(&{text_expr});\n"
            ));
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"button\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_text_content({var}, {lbl:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::add_event_listener({var}, \"click\", {action});\n"
                ));
            }
        }
        NodeKind::Image(src) => {
            let src_val = node.src.as_deref().unwrap_or(src.as_str());
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"img\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"src\", {src_val:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
        }
        NodeKind::TextInput => {
            let placeholder = node.placeholder.as_deref().unwrap_or("Enter text");
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"input\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"type\", \"text\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"placeholder\", {placeholder:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let tag = "div";
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element({tag:?});\n"
            ));

            // Set flex-direction for Row
            if matches!(node.kind, NodeKind::Row) {
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::set_style_property({var}, \"flex-direction\", \"row\");\n"
                ));
            }

            gen_dom_style_calls(&node.style, &var, out, &indent);

            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::add_event_listener({var}, \"click\", {action});\n"
                ));
            }

            for child in &node.children {
                let child_var = gen_dom_node(child, out, counter, depth, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::append_child({var}, {child_var});\n"
                ));
            }
        }
    }

    var
}

fn gen_dom_style_calls(style: &StyleDecl, var: &str, out: &mut String, indent: &str) {
    let sp = |prop: &str, val: &str| {
        format!("{indent}w3cos_runtime::dom::set_style_property({var}, {prop:?}, {val:?});\n")
    };

    if let Some(gap) = style.gap {
        out.push_str(&sp("gap", &format!("{gap}px")));
    }
    if let Some(p) = style.padding {
        out.push_str(&sp("padding", &format!("{p}px")));
    }
    if let Some(fs) = style.font_size {
        out.push_str(&sp("font-size", &format!("{fs}px")));
    }
    if let Some(fw) = style.font_weight {
        out.push_str(&sp("font-weight", &fw.to_string()));
    }
    if let Some(ref c) = style.color {
        out.push_str(&sp("color", c));
    }
    if let Some(ref bg) = style.background {
        out.push_str(&sp("background-color", bg));
    }
    if let Some(br) = style.border_radius {
        out.push_str(&sp("border-radius", &format!("{br}px")));
    }
    if let Some(bw) = style.border_width {
        out.push_str(&sp("border-width", &format!("{bw}px")));
    }
    if let Some(ref bc) = style.border_color {
        out.push_str(&sp("border-color", bc));
    }
    if let Some(ref ai) = style.align_items {
        out.push_str(&sp("align-items", ai));
    }
    if let Some(ref jc) = style.justify_content {
        out.push_str(&sp("justify-content", jc));
    }
    if let Some(ref w) = style.width {
        out.push_str(&sp("width", w));
    }
    if let Some(ref h) = style.height {
        out.push_str(&sp("height", h));
    }
    if let Some(fg) = style.flex_grow {
        out.push_str(&sp("flex-grow", &fg.to_string()));
    }
    if let Some(ref d) = style.display {
        out.push_str(&sp("display", d));
    }
    if let Some(ref p) = style.position {
        out.push_str(&sp("position", p));
    }
    if let Some(ref ov) = style.overflow {
        out.push_str(&sp("overflow", ov));
    }
    if let Some(ref t) = style.top { out.push_str(&sp("top", t)); }
    if let Some(ref r) = style.right { out.push_str(&sp("right", r)); }
    if let Some(ref b) = style.bottom { out.push_str(&sp("bottom", b)); }
    if let Some(ref l) = style.left { out.push_str(&sp("left", l)); }
    if let Some(zi) = style.z_index {
        out.push_str(&sp("z-index", &zi.to_string()));
    }
}

#[cfg(test)]
mod tests {
    use crate::css_parser;
    use crate::parser::{AppTree, Node, NodeKind, StyleDecl};

    use super::*;

    fn empty_sheet() -> Stylesheet {
        css_parser::Stylesheet::empty()
    }

    fn test_node(kind: NodeKind, style: StyleDecl) -> Node {
        Node {
            kind,
            style,
            children: vec![],
            text: None,
            label: None,
            on_click: None,
            src: None,
            placeholder: None,
            class_name: None,
        }
    }

    fn test_tree(root: Node) -> AppTree {
        AppTree {
            root,
            signals: vec![],
            css_imports: vec![],
        }
    }

    #[test]
    fn codegen_text_produces_component_text() {
        let mut node = test_node(NodeKind::Text("hello".into()), StyleDecl::default());
        node.text = Some("hello".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::text(\"hello\""));
        assert!(rust.contains("fn build_ui()"));
        assert!(rust.contains("w3cos_runtime::run_app"));
    }

    #[test]
    fn codegen_button_produces_component_button() {
        let mut node = test_node(NodeKind::Button("click me".into()), StyleDecl::default());
        node.label = Some("click me".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::button(\"click me\""));
    }

    #[test]
    fn codegen_column_with_children() {
        let mut root = test_node(NodeKind::Column, StyleDecl::default());
        let mut a = test_node(NodeKind::Text("a".into()), StyleDecl::default());
        a.text = Some("a".into());
        let mut b = test_node(NodeKind::Text("b".into()), StyleDecl::default());
        b.text = Some("b".into());
        root.children = vec![a, b];
        let rust = generate(&test_tree(root), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::column"));
        assert!(rust.contains("Component::text(\"a\""));
        assert!(rust.contains("Component::text(\"b\""));
        assert!(rust.contains("vec!["));
    }

    #[test]
    fn codegen_text_input_produces_component_text_input() {
        let mut node = test_node(NodeKind::TextInput, StyleDecl::default());
        node.placeholder = Some("Enter name".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::text_input"));
        assert!(rust.contains("\"Enter name\""));
    }

    #[test]
    fn codegen_row_with_style() {
        let mut style = StyleDecl::default();
        style.gap = Some(10.0);
        let rust = generate(&test_tree(test_node(NodeKind::Row, style)), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::row"));
        assert!(rust.contains("gap: 10_f32"));
    }

    #[test]
    fn codegen_style_color_and_background() {
        let mut style = StyleDecl::default();
        style.color = Some("#fff".into());
        style.background = Some("#e94560".into());
        let mut node = test_node(NodeKind::Text("styled".into()), style);
        node.text = Some("styled".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Color::from_hex(\"#fff\")"));
        assert!(rust.contains("Color::from_hex(\"#e94560\")"));
    }

    #[test]
    fn codegen_image_produces_component_image() {
        let mut node = test_node(NodeKind::Image("path.png".into()), StyleDecl::default());
        node.src = Some("path.png".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::image(\"path.png\""));
    }

    #[test]
    fn codegen_with_css_stylesheet() {
        let css = ".title { font-size: 24; color: #e94560; }";
        let sheet = css_parser::parse_css(css);
        let mut node = test_node(NodeKind::Text("Hello".into()), StyleDecl::default());
        node.text = Some("Hello".into());
        node.class_name = Some("title".into());
        let rust = generate(&test_tree(node), &sheet).unwrap();
        assert!(rust.contains("font_size: 24_f32"));
        assert!(rust.contains("Color::from_hex(\"#e94560\")"));
    }

    #[test]
    fn codegen_css_overridden_by_inline() {
        let css = ".title { color: red; font-size: 24; }";
        let sheet = css_parser::parse_css(css);
        let mut style = StyleDecl::default();
        style.color = Some("#fff".into());
        let mut node = test_node(NodeKind::Text("Hello".into()), style);
        node.text = Some("Hello".into());
        node.class_name = Some("title".into());
        let rust = generate(&test_tree(node), &sheet).unwrap();
        assert!(rust.contains("Color::from_hex(\"#fff\")"));
        assert!(rust.contains("font_size: 24_f32"));
    }
}
