use anyhow::Result;
use crate::parser::{AppTree, Node, NodeKind, StyleDecl};
#[allow(unused_imports)]
use anyhow::Context;

/// Generate a complete Rust main.rs that builds and runs a W3C OS application.
pub fn generate(tree: &AppTree) -> Result<String> {
    let component_code = gen_node(&tree.root, 0);

    Ok(format!(
r#"//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{{Component, Style}};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {{
    let root = build_ui();
    w3cos_runtime::run_app(root).expect("W3C OS app crashed");
}}

fn build_ui() -> Component {{
{component_code}
}}
"#
    ))
}

/// Generate a Cargo.toml for the compiled application.
pub fn generate_cargo_toml(_output_dir: &std::path::Path) -> Result<String> {
    let workspace_root = find_workspace_root()?;
    let runtime_path = workspace_root.join("crates/w3cos-runtime");
    let std_path = workspace_root.join("crates/w3cos-std");

    Ok(format!(
r#"[package]
name = "w3cos-app"
version = "0.1.0"
edition = "2024"

[dependencies]
w3cos-runtime = {{ path = "{runtime}" }}
w3cos-std = {{ path = "{std_}" }}
"#,
        runtime = runtime_path.display(),
        std_ = std_path.display(),
    ))
}

fn find_workspace_root() -> Result<std::path::PathBuf> {
    let exe = std::env::current_exe()
        .unwrap_or_else(|_| std::env::current_dir().unwrap());
    let mut dir = exe.parent().unwrap().to_path_buf();

    // Walk up from the executable location
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    // Fallback: walk up from current working directory
    let mut dir = std::env::current_dir()?;
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    anyhow::bail!(
        "Could not find w3cos workspace root. Run from within the w3cos project directory."
    )
}

fn gen_node(node: &Node, depth: usize) -> String {
    let indent = "    ".repeat(depth + 1);
    let style_code = gen_style(&node.style, depth + 1);

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            format!(
                "{indent}Component::text({text:?}, {style_code})"
            )
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            format!(
                "{indent}Component::button({lbl:?}, {style_code})"
            )
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let constructor = match &node.kind {
                NodeKind::Column => "Component::column",
                NodeKind::Row => "Component::row",
                NodeKind::Box => "Component::boxed",
                _ => unreachable!(),
            };
            let children_code = if node.children.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = node.children.iter()
                    .map(|c| gen_node(c, depth + 2))
                    .collect();
                format!("vec![\n{},\n{indent}]", items.join(",\n"))
            };
            format!(
                "{indent}{constructor}({style_code}, {children_code})"
            )
        }
    }
}

fn gen_style(s: &StyleDecl, depth: usize) -> String {
    let indent = "    ".repeat(depth);
    let mut fields = Vec::new();

    if let Some(gap) = s.gap {
        fields.push(format!("gap: {gap}_f32"));
    }
    if let Some(p) = s.padding {
        fields.push(format!("padding: Edges::all({p}_f32)"));
    }
    if let Some(fs) = s.font_size {
        fields.push(format!("font_size: {fs}_f32"));
    }
    if let Some(fw) = s.font_weight {
        fields.push(format!("font_weight: {fw}"));
    }
    if let Some(ref c) = s.color {
        fields.push(format!("color: Color::from_hex({c:?})"));
    }
    if let Some(ref bg) = s.background {
        fields.push(format!("background: Color::from_hex({bg:?})"));
    }
    if let Some(br) = s.border_radius {
        fields.push(format!("border_radius: {br}_f32"));
    }
    if let Some(bw) = s.border_width {
        fields.push(format!("border_width: {bw}_f32"));
    }
    if let Some(ref bc) = s.border_color {
        fields.push(format!("border_color: Color::from_hex({bc:?})"));
    }
    if let Some(ref ai) = s.align_items {
        let variant = match ai.as_str() {
            "center" => "AlignItems::Center",
            "flex-start" | "flexStart" => "AlignItems::FlexStart",
            "flex-end" | "flexEnd" => "AlignItems::FlexEnd",
            "baseline" => "AlignItems::Baseline",
            _ => "AlignItems::Stretch",
        };
        fields.push(format!("align_items: {variant}"));
    }
    if let Some(ref jc) = s.justify_content {
        let variant = match jc.as_str() {
            "center" => "JustifyContent::Center",
            "flex-end" | "flexEnd" => "JustifyContent::FlexEnd",
            "space-between" | "spaceBetween" => "JustifyContent::SpaceBetween",
            "space-around" | "spaceAround" => "JustifyContent::SpaceAround",
            "space-evenly" | "spaceEvenly" => "JustifyContent::SpaceEvenly",
            _ => "JustifyContent::FlexStart",
        };
        fields.push(format!("justify_content: {variant}"));
    }
    if let Some(fg) = s.flex_grow {
        fields.push(format!("flex_grow: {fg}_f32"));
    }
    if let Some(ref d) = s.display {
        let variant = match d.as_str() {
            "block" => "Display::Block",
            "grid" => "Display::Grid",
            "inline" => "Display::Inline",
            "inline-block" => "Display::InlineBlock",
            "none" => "Display::None",
            _ => "Display::Flex",
        };
        fields.push(format!("display: {variant}"));
    }
    if let Some(ref p) = s.position {
        let variant = match p.as_str() {
            "absolute" => "Position::Absolute",
            "fixed" => "Position::Fixed",
            "sticky" => "Position::Sticky",
            _ => "Position::Relative",
        };
        fields.push(format!("position: {variant}"));
    }
    if let Some(ref ov) = s.overflow {
        let variant = match ov.as_str() {
            "hidden" => "Overflow::Hidden",
            "scroll" => "Overflow::Scroll",
            "auto" => "Overflow::Auto",
            _ => "Overflow::Visible",
        };
        fields.push(format!("overflow: {variant}"));
    }

    if fields.is_empty() {
        "Style::default()".to_string()
    } else {
        let joined = fields.join(&format!(",\n{indent}    "));
        format!("Style {{\n{indent}    {joined},\n{indent}    ..Style::default()\n{indent}}}")
    }
}
