use crate::css_parser::{MatchContext, PseudoState, Stylesheet};
use crate::css_values::{self, parse_animation, parse_box_shadow, parse_transform};
use crate::parser::{AppTree, Node, NodeKind, SignalDecl, StyleDecl};
use crate::style_matcher::{self, ResolveViewport};
#[allow(unused_imports)]
use anyhow::Context;
use anyhow::Result;
use w3cos_std::style::{SafeAreaEdge, Spacing};

/// Generate a complete Rust main.rs that builds and runs a W3C OS application.
pub fn generate(tree: &AppTree, stylesheet: &Stylesheet) -> Result<String> {
    let is_reactive = !tree.signals.is_empty();
    let signal_names: Vec<&str> = tree.signals.iter().map(|s| s.name.as_str()).collect();
    let component_code = gen_node(&tree.root, 0, &signal_names, stylesheet, 1, 1);

    if is_reactive {
        let signal_inits = gen_signal_inits(&tree.signals);
        Ok(format!(
            r#"//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{{Component, EventAction, Style}};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {{
    w3cos_runtime::run_app(build_ui).expect("W3C OS app crashed");
}}

fn build_ui() -> Component {{
{signal_inits}
{component_code}
}}
"#
        ))
    } else {
        Ok(format!(
            r#"//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{{Component, Style}};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {{
    w3cos_runtime::run_app(build_ui).expect("W3C OS app crashed");
}}

fn build_ui() -> Component {{
{component_code}
}}
"#
        ))
    }
}

fn gen_signal_inits(signals: &[SignalDecl]) -> String {
    if signals.is_empty() {
        return String::new();
    }
    let register: Vec<String> = signals
        .iter()
        .map(|sig| {
            let initializer = sig.initial.rust_initializer();
            format!(
                "        w3cos_runtime::state::register_signal_name({name:?});\n        let _ = {initializer};",
                name = sig.name,
            )
        })
        .collect();
    format!(
        "    w3cos_runtime::state::ensure_signals(|| {{\n{register}\n    }});\n",
        register = register.join("\n"),
    )
}

/// Options that influence generated Cargo.toml / runtime features.
#[derive(Debug, Clone, Copy, Default)]
pub struct CompileOptions {
    /// Enable Chrome DevTools Protocol (CDP) server in w3cos-runtime.
    pub devtools: bool,
}

/// Generate a Cargo.toml for the compiled application.
pub fn generate_cargo_toml(
    _output_dir: &std::path::Path,
    options: &CompileOptions,
) -> Result<String> {
    let workspace_root = find_workspace_root()?;
    let runtime_path = workspace_root.join("crates/w3cos-runtime");
    let std_path = workspace_root.join("crates/w3cos-std");
    let runtime_features = if options.devtools {
        r#", features = ["devtools"]"#
    } else {
        ""
    };

    Ok(format!(
        r#"[package]
name = "w3cos-app"
version = "0.1.0"
edition = "2024"

[dependencies]
w3cos-runtime = {{ path = "{runtime}"{runtime_features} }}
w3cos-std = {{ path = "{std_}" }}
"#,
        runtime = runtime_path.display(),
        std_ = std_path.display(),
    ))
}

pub(crate) fn find_workspace_root() -> Result<std::path::PathBuf> {
    let exe = std::env::current_exe().unwrap_or_else(|_| std::env::current_dir().unwrap());
    let mut dir = exe.parent().unwrap().to_path_buf();

    // Walk up from the executable location
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    // Fallback: walk up from current working directory
    let mut dir = std::env::current_dir()?;
    for _ in 0..10 {
        if dir.join("Cargo.toml").exists() {
            let content = std::fs::read_to_string(dir.join("Cargo.toml"))?;
            if content.contains("[workspace]") {
                return Ok(dir);
            }
        }
        if !dir.pop() {
            break;
        }
    }

    anyhow::bail!(
        "Could not find w3cos workspace root. Run from within the w3cos project directory."
    )
}

pub(crate) fn gen_node(
    node: &Node,
    depth: usize,
    signal_names: &[&str],
    stylesheet: &Stylesheet,
    child_index: usize,
    sibling_count: usize,
) -> String {
    let indent = "    ".repeat(depth + 1);
    let body = if let Some((sig, val)) = &node.show_when {
        let sig_id = signal_index(sig, signal_names);
        if node.children.len() == 1 {
            let inner =
                gen_node_inner(&node.children[0], depth + 1, signal_names, stylesheet, 1, 1);
            return format!(
                "{indent}{{\n{indent}    let mut __show_comp = {{\n{inner}\n{indent}    }};\n{indent}    if w3cos_runtime::state::get_signal({sig_id}) != {val} {{\n{indent}        __show_comp.style.display = Display::None;\n{indent}    }}\n{indent}    __show_comp\n{indent}}}"
            );
        }
        let sib = node.children.len();
        let items: Vec<String> = node
            .children
            .iter()
            .enumerate()
            .map(|(i, c)| gen_node(c, depth + 2, signal_names, stylesheet, i + 1, sib))
            .collect();
        let inner = format!(
            "{indent}Component::column(Style::default(), vec![\n{},{indent}])",
            items.join(",\n")
        );
        return format!(
            "{indent}{{\n{indent}    let mut __show_style = Style::default();\n{indent}    if w3cos_runtime::state::get_signal({sig_id}) != {val} {{\n{indent}        __show_style.display = Display::None;\n{indent}    }}\n{indent}    Component::column(__show_style, vec![\n{inner}\n{indent}    ])\n{indent}}}"
        );
    } else {
        gen_node_inner(
            node,
            depth,
            signal_names,
            stylesheet,
            child_index,
            sibling_count,
        )
    };
    body
}

fn gen_node_inner(
    node: &Node,
    depth: usize,
    signal_names: &[&str],
    stylesheet: &Stylesheet,
    child_index: usize,
    sibling_count: usize,
) -> String {
    let indent = "    ".repeat(depth + 1);
    let class_storage = style_matcher::class_names_vec(node);
    let class_refs: Vec<&str> = class_storage.iter().map(|s| s.as_str()).collect();
    let match_ctx = MatchContext {
        element_kind: style_matcher::dom_tag(node),
        class_names: &class_refs,
        attributes: &[],
        child_index,
        sibling_count,
        child_count: node.children.len(),
        pseudo_state: PseudoState::default(),
    };
    let resolved =
        style_matcher::resolve_style_ctx(node, stylesheet, &match_ctx, &ResolveViewport::default());
    let style_code = gen_style(&resolved, depth + 1, signal_names);

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            let text_expr = gen_text_expr(text, signal_names);
            let mut text_style = resolved.clone();
            if text_style.display.is_none() {
                text_style.display = Some("inline-block".into());
            }
            if text_style.flex_shrink.is_none() {
                text_style.flex_shrink = Some(0.0);
            }
            let style_code = gen_style(&text_style, depth + 1, signal_names);
            format!("{indent}Component::text({text_expr}, {style_code})")
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                format!("{indent}Component::button_with_click({lbl:?}, {style_code}, {action})")
            } else {
                format!("{indent}Component::button({lbl:?}, {style_code})")
            }
        }
        NodeKind::Image(src) => {
            let src_val = node.src.as_deref().unwrap_or(src.as_str());
            format!("{indent}Component::image({src_val:?}, {style_code})")
        }
        NodeKind::TextInput => {
            let placeholder = node.placeholder.as_deref().unwrap_or("Enter text");
            format!("{indent}Component::text_input(\"\", {placeholder:?}, {style_code})")
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let constructor = match &node.kind {
                NodeKind::Column => "Component::column",
                NodeKind::Row => "Component::row",
                NodeKind::Box => "Component::boxed",
                _ => unreachable!(),
            };
            let mut children_code = if node.children.is_empty() {
                "vec![]".to_string()
            } else {
                let sib = node.children.len();
                let items: Vec<String> = node
                    .children
                    .iter()
                    .enumerate()
                    .map(|(i, c)| gen_node(c, depth + 2, signal_names, stylesheet, i + 1, sib))
                    .collect();
                format!("vec![\n{},\n{indent}]", items.join(",\n"))
            };
            if let Some(item_count) = node.style.virtual_count
                && let Some(template) = node.children.first()
            {
                let template_code = gen_node(
                    template,
                    depth + 2,
                    signal_names,
                    stylesheet,
                    1,
                    node.children.len(),
                );
                let estimated = node.style.estimated_item_height.unwrap_or(72.0);
                let overscan = node.style.virtual_overscan.unwrap_or(240.0);
                return format!(
                    "{indent}Component::virtual_list({item_count}, {estimated:?}, {overscan:?}, {style_code}, {template_code})"
                );
            }
            if let Some(repeat) = node.repeat
                && !node.children.is_empty()
            {
                children_code = format!(
                    "{{\n{indent}    let __repeat_template = {children_code};\n{indent}    let mut __repeat_children = Vec::with_capacity(__repeat_template.len() * {repeat});\n{indent}    for _ in 0..{repeat} {{\n{indent}        __repeat_children.extend(__repeat_template.iter().cloned());\n{indent}    }}\n{indent}    __repeat_children\n{indent}}}"
                );
            }
            if node.on_click.is_some() || node.sticky_counter.is_some() {
                let mut assignments = String::new();
                if let Some(ref action_str) = node.on_click {
                    let action = gen_event_action(action_str, signal_names);
                    assignments.push_str(&format!("{indent}    __comp.on_click = {action};\n"));
                }
                if let Some(ref signal_name) = node.sticky_counter {
                    let signal_id = signal_index(signal_name, signal_names);
                    assignments.push_str(&format!(
                        "{indent}    __comp.sticky_counter_signal = Some({signal_id});\n"
                    ));
                }
                format!(
                    "{indent}{{\n{indent}    let mut __comp = {constructor}({style_code}, {children_code});\n{assignments}{indent}    __comp\n{indent}}}"
                )
            } else {
                format!("{indent}{constructor}({style_code}, {children_code})")
            }
        }
    }
}

fn gen_text_expr(text: &str, signal_names: &[&str]) -> String {
    if !text.contains('{') {
        return format!("{text:?}");
    }
    // Raw strings avoid Rust 2024 `{ident}` implicit format interpolation in generated code.
    let mut expr = format!("r{text:?}.to_string()");
    for (i, name) in signal_names.iter().enumerate() {
        let placeholder = format!("{{{name}}}");
        if text.contains(&placeholder) {
            expr = format!(
                "{expr}.replace(r{placeholder:?}, &w3cos_runtime::state::get_signal_text({i}))"
            );
        }
    }
    expr
}

fn gen_event_action(action_str: &str, signal_names: &[&str]) -> String {
    let parts: Vec<&str> = action_str.split(':').collect();
    if parts.first().is_some_and(|part| part.trim() == "speech") {
        return match parts.get(1).map(|part| part.trim()) {
            Some("start") if parts.len() >= 10 => {
                let signal_id = |index: usize| {
                    let name = parts[index].trim();
                    signal_names
                        .iter()
                        .position(|&candidate| candidate == name)
                        .unwrap_or(0)
                };
                let transcript_signal = signal_id(2);
                let final_signal = signal_id(3);
                let confidence_signal = signal_id(4);
                let status_signal = signal_id(5);
                let lang = parts[6].trim();
                let flag = |index: usize| matches!(parts[index].trim(), "1" | "true");
                let process_locally = flag(7);
                let continuous = flag(8);
                let interim_results = flag(9);
                format!(
                    "EventAction::SpeechRecognitionStart {{ transcript_signal: {transcript_signal}, final_signal: {final_signal}, confidence_signal: {confidence_signal}, status_signal: {status_signal}, lang: {lang:?}.to_string(), process_locally: {process_locally}, continuous: {continuous}, interim_results: {interim_results} }}"
                )
            }
            Some("stop") => {
                if parts.len() >= 4 {
                    let signal_name = parts[2].trim();
                    let signal_id = signal_names
                        .iter()
                        .position(|&candidate| candidate == signal_name)
                        .unwrap_or(0);
                    let value = parts[3].trim().parse::<i64>().unwrap_or(0);
                    format!(
                        "EventAction::SpeechRecognitionStop {{ after_signal: Some({signal_id}), after_value: {value} }}"
                    )
                } else {
                    "EventAction::SpeechRecognitionStop { after_signal: None, after_value: 0 }"
                        .to_string()
                }
            }
            _ => "EventAction::None".to_string(),
        };
    }
    if !parts.is_empty() && parts[0].trim() == "notify" {
        if parts.len() < 3 {
            return "EventAction::None".to_string();
        }
        let title = parts[1].trim();
        let body = parts[2..].join(":");
        return format!(
            "EventAction::Notify({:?}.to_string(), {:?}.to_string())",
            title, body
        );
    }

    if parts.len() >= 2 && parts[0].trim() == "history" {
        let op = parts[1].trim();
        let route_name = parts.get(2).map(|s| s.trim()).unwrap_or("route");
        let route_id = signal_names
            .iter()
            .position(|&n| n == route_name)
            .unwrap_or(0);
        return match op {
            "push" => {
                let value = parts
                    .get(3)
                    .and_then(|v| v.trim().parse::<i64>().ok())
                    .unwrap_or(0);
                let path = parts.get(4..).map(|p| p.join(":")).unwrap_or_default();
                format!(
                    "EventAction::HistoryPush {{ route_signal: {route_id}, route_value: {value}, path: {:?}.to_string() }}",
                    path
                )
            }
            "back" => format!("EventAction::HistoryBack {{ route_signal: {route_id} }}"),
            _ => "EventAction::None".to_string(),
        };
    }

    if parts.len() >= 5 && parts[0].trim() == "fetch" {
        let status_name = parts[2].trim();
        let bytes_name = parts[3].trim();
        let status_id = signal_names
            .iter()
            .position(|&n| n == status_name)
            .unwrap_or(0);
        let bytes_id = signal_names
            .iter()
            .position(|&n| n == bytes_name)
            .unwrap_or(0);
        let url = parts[4..].join(":");
        return format!(
            "EventAction::FetchGet {{ url: {:?}.to_string(), status_signal: {status_id}, bytes_signal: {bytes_id} }}",
            url
        );
    }

    if parts.len() < 2 {
        return "EventAction::None".to_string();
    }

    let action_type = parts[0].trim();
    let signal_name = parts[1].trim();
    let signal_id = signal_names
        .iter()
        .position(|&n| n == signal_name)
        .unwrap_or(0);

    match action_type {
        "increment" => format!("EventAction::Increment({signal_id})"),
        "decrement" => format!("EventAction::Decrement({signal_id})"),
        "toggle" => format!("EventAction::Toggle({signal_id})"),
        "set" => {
            let value = parts
                .get(2)
                .and_then(|v| v.trim().parse::<i64>().ok())
                .unwrap_or(0);
            format!("EventAction::Set({signal_id}, {value})")
        }
        _ => "EventAction::None".to_string(),
    }
}

fn signal_index(name: &str, signal_names: &[&str]) -> usize {
    signal_names.iter().position(|&n| n == name).unwrap_or(0)
}

fn gen_transition_rust(value: &str) -> String {
    let parts: Vec<&str> = value.split_whitespace().collect();
    let property = match parts.first().copied().unwrap_or("all") {
        "all" => "TransitionProperty::All",
        "opacity" => "TransitionProperty::Opacity",
        "transform" => "TransitionProperty::Transform",
        "background" | "background-color" => "TransitionProperty::Background",
        "color" => "TransitionProperty::Color",
        _ => "TransitionProperty::All",
    };
    let duration_ms = parts
        .get(1)
        .and_then(|s| {
            if let Some(ms) = s.strip_suffix("ms") {
                ms.parse::<u32>().ok()
            } else if let Some(sec) = s.strip_suffix('s') {
                sec.parse::<f32>().ok().map(|v| (v * 1000.0) as u32)
            } else {
                s.parse().ok()
            }
        })
        .unwrap_or(300);
    let easing = match parts.get(2).copied().unwrap_or("ease") {
        "linear" => "Easing::Linear",
        "ease-in" => "Easing::EaseIn",
        "ease-out" => "Easing::EaseOut",
        "ease-in-out" => "Easing::EaseInOut",
        _ => "Easing::Ease",
    };
    format!(
        "Some(Transition {{ property: {property}, duration_ms: {duration_ms}, easing: {easing}, delay_ms: 0 }})"
    )
}

// ---------------------------------------------------------------------------
// Style codegen helpers
// ---------------------------------------------------------------------------

fn gen_spacing(s: Spacing) -> String {
    match s {
        Spacing::Px(v) => format!("Spacing::Px({v}_f32)"),
        Spacing::SafeAreaInset(SafeAreaEdge::Top) => {
            "Spacing::SafeAreaInset(SafeAreaEdge::Top)".to_string()
        }
        Spacing::SafeAreaInset(SafeAreaEdge::Right) => {
            "Spacing::SafeAreaInset(SafeAreaEdge::Right)".to_string()
        }
        Spacing::SafeAreaInset(SafeAreaEdge::Bottom) => {
            "Spacing::SafeAreaInset(SafeAreaEdge::Bottom)".to_string()
        }
        Spacing::SafeAreaInset(SafeAreaEdge::Left) => {
            "Spacing::SafeAreaInset(SafeAreaEdge::Left)".to_string()
        }
        Spacing::KeyboardInsetHeight => "Spacing::KeyboardInsetHeight".to_string(),
        Spacing::Composite {
            px,
            safe_area,
            keyboard_inset,
        } => {
            let edge = safe_area.map(|e| match e {
                SafeAreaEdge::Top => "Some(SafeAreaEdge::Top)",
                SafeAreaEdge::Right => "Some(SafeAreaEdge::Right)",
                SafeAreaEdge::Bottom => "Some(SafeAreaEdge::Bottom)",
                SafeAreaEdge::Left => "Some(SafeAreaEdge::Left)",
            });
            if edge.is_none() && !keyboard_inset {
                format!("Spacing::Px({px}_f32)")
            } else {
                format!(
                    "Spacing::Composite {{ px: {px}_f32, safe_area: {}, keyboard_inset: {keyboard_inset} }}",
                    edge.unwrap_or("None")
                )
            }
        }
    }
}

fn gen_padding_edges(s: &StyleDecl) -> Option<String> {
    let (t, r, b, l) = if s.padding_top.is_some()
        || s.padding_right.is_some()
        || s.padding_bottom.is_some()
        || s.padding_left.is_some()
    {
        let fallback = s.padding.unwrap_or(Spacing::Px(0.0));
        let t = s.padding_top.unwrap_or(fallback);
        let r = s.padding_right.unwrap_or(fallback);
        let b = s.padding_bottom.unwrap_or(fallback);
        let l = s.padding_left.unwrap_or(fallback);
        (t, r, b, l)
    } else if let Some(p) = s.padding {
        (p, p, p, p)
    } else {
        return None;
    };

    if t == r && r == b && b == l {
        if let Spacing::Px(v) = t {
            return Some(format!("padding: Edges::all({v}_f32)"));
        }
        let s = gen_spacing(t);
        return Some(format!(
            "padding: Edges {{ top: {s}, right: {s}, bottom: {s}, left: {s} }}"
        ));
    }
    if t == b && r == l {
        if let (Spacing::Px(x), Spacing::Px(y)) = (r, t) {
            return Some(format!("padding: Edges::xy({x}_f32, {y}_f32)"));
        }
    }
    Some(format!(
        "padding: Edges {{ top: {}, right: {}, bottom: {}, left: {} }}",
        gen_spacing(t),
        gen_spacing(r),
        gen_spacing(b),
        gen_spacing(l),
    ))
}

fn gen_style(s: &StyleDecl, depth: usize, signal_names: &[&str]) -> String {
    let indent = "    ".repeat(depth);
    let mut fields = Vec::new();

    if let Some(gap) = s.gap {
        fields.push(format!("gap: {gap}_f32"));
    }
    if let Some(padding) = gen_padding_edges(s) {
        fields.push(padding);
    }
    if let Some(fs) = s.font_size {
        fields.push(format!("font_size: {fs}_f32"));
    }
    if let Some(fw) = s.font_weight {
        fields.push(format!("font_weight: {fw}"));
    }
    if let Some(lh) = s.line_height {
        fields.push(format!("line_height: {lh}_f32"));
    }
    if let Some(ref c) = s.color {
        fields.push(format!("color: Color::from_hex({c:?})"));
    }
    if s.background_from_signal.is_none() {
        if let Some(ref bg) = s.background {
            fields.push(format!("background: Color::from_hex({bg:?})"));
        }
    }
    if let Some(br) = s.border_radius {
        fields.push(format!("border_radius: {br}_f32"));
    }
    if let Some(bw) = s.border_width {
        fields.push(format!("border_width: {bw}_f32"));
    }
    if let Some(ref bc) = s.border_color {
        fields.push(format!("border_color: Color::from_hex({bc:?})"));
    }
    if let Some(ref ai) = s.align_items {
        let variant = match ai.as_str() {
            "center" => "AlignItems::Center",
            "flex-start" | "flexStart" => "AlignItems::FlexStart",
            "flex-end" | "flexEnd" => "AlignItems::FlexEnd",
            "baseline" => "AlignItems::Baseline",
            _ => "AlignItems::Stretch",
        };
        fields.push(format!("align_items: {variant}"));
    }
    if let Some(ref jc) = s.justify_content {
        let variant = match jc.as_str() {
            "center" => "JustifyContent::Center",
            "flex-end" | "flexEnd" => "JustifyContent::FlexEnd",
            "space-between" | "spaceBetween" => "JustifyContent::SpaceBetween",
            "space-around" | "spaceAround" => "JustifyContent::SpaceAround",
            "space-evenly" | "spaceEvenly" => "JustifyContent::SpaceEvenly",
            _ => "JustifyContent::FlexStart",
        };
        fields.push(format!("justify_content: {variant}"));
    }
    if let Some(ref w) = s.width {
        fields.push(format!("width: {}", gen_dimension(w)));
    }
    if let Some(ref h) = s.height {
        fields.push(format!("height: {}", gen_dimension(h)));
    }
    if let Some(fg) = s.flex_grow {
        fields.push(format!("flex_grow: {fg}_f32"));
    }
    if let Some(fs) = s.flex_shrink {
        fields.push(format!("flex_shrink: {fs}_f32"));
    }
    if let Some(ref d) = s.display {
        let variant = match d.as_str() {
            "block" => "Display::Block",
            "grid" => "Display::Grid",
            "inline" => "Display::Inline",
            "inline-block" => "Display::InlineBlock",
            "none" => "Display::None",
            _ => "Display::Flex",
        };
        fields.push(format!("display: {variant}"));
    }
    if let Some(ref t) = s.top {
        fields.push(format!("top: {}", gen_dimension(t)));
    }
    if let Some(ref r) = s.right {
        fields.push(format!("right: {}", gen_dimension(r)));
    }
    if let Some(ref b) = s.bottom {
        fields.push(format!("bottom: {}", gen_dimension(b)));
    }
    if let Some(ref l) = s.left {
        fields.push(format!("left: {}", gen_dimension(l)));
    }
    if let Some(zi) = s.z_index {
        fields.push(format!("z_index: {zi}"));
    }
    if let Some(ref p) = s.position {
        let variant = match p.as_str() {
            "static" => "Position::Static",
            "absolute" => "Position::Absolute",
            "fixed" => "Position::Fixed",
            "sticky" => "Position::Sticky",
            _ => "Position::Static",
        };
        fields.push(format!("position: {variant}"));
    }
    if let Some(ref ov) = s.overflow {
        let variant = match ov.as_str() {
            "hidden" => "Overflow::Hidden",
            "scroll" => "Overflow::Scroll",
            "auto" => "Overflow::Auto",
            _ => "Overflow::Visible",
        };
        fields.push(format!("overflow: {variant}"));
    }
    if let Some(ref behavior) = s.overscroll_behavior {
        let variant = match behavior.as_str() {
            "contain" => "OverscrollBehavior::Contain",
            "none" => "OverscrollBehavior::None",
            _ => "OverscrollBehavior::Auto",
        };
        fields.push(format!("overscroll_behavior: {variant}"));
    }
    if let Some(ref target) = s.scroll_initial_target {
        let variant = match target.as_str() {
            "nearest" => "ScrollInitialTarget::Nearest",
            _ => "ScrollInitialTarget::None",
        };
        fields.push(format!("scroll_initial_target: {variant}"));
    }
    if let Some(m) = s.margin {
        if let Spacing::Px(v) = m {
            fields.push(format!("margin: Edges::all({v}_f32)"));
        } else {
            fields.push(format!("margin: Edges::all({})", gen_spacing(m)));
        }
    }
    if let Some(ref fw) = s.flex_wrap {
        let variant = match fw.as_str() {
            "wrap" => "FlexWrap::Wrap",
            "wrap-reverse" | "wrapReverse" => "FlexWrap::WrapReverse",
            _ => "FlexWrap::NoWrap",
        };
        fields.push(format!("flex_wrap: {variant}"));
    }
    if let Some(ref ws) = s.white_space {
        let variant = match ws.as_str() {
            "nowrap" | "noWrap" => "WhiteSpace::NoWrap",
            "pre" => "WhiteSpace::Pre",
            "pre-wrap" | "preWrap" => "WhiteSpace::PreWrap",
            "pre-line" | "preLine" => "WhiteSpace::PreLine",
            _ => "WhiteSpace::Normal",
        };
        fields.push(format!("white_space: {variant}"));
    }
    if let Some(ref mw) = s.min_width {
        fields.push(format!("min_width: {}", gen_dimension(mw)));
    }
    if let Some(ref mh) = s.min_height {
        fields.push(format!("min_height: {}", gen_dimension(mh)));
    }
    if let Some(ref ta) = s.text_align {
        let variant = match ta.as_str() {
            "center" => "TextAlign::Center",
            "right" => "TextAlign::Right",
            "justify" => "TextAlign::Justify",
            _ => "TextAlign::Left",
        };
        fields.push(format!("text_align: {variant}"));
    }
    if let Some(op) = s.opacity {
        fields.push(format!("opacity: {op}_f32"));
    }
    if let Some(ref sig) = s.opacity_from_signal {
        let id = signal_index(sig, signal_names);
        fields.push(format!(
            "opacity: w3cos_runtime::state::get_signal({id}) as f32 / 100.0"
        ));
    }
    if let Some((ref sig, ref color_a, ref color_b)) = s.background_from_signal {
        let id = signal_index(sig, signal_names);
        fields.push(format!(
            "background: if w3cos_runtime::state::get_signal({id}) == 0 {{ Color::from_hex({color_a:?}) }} else {{ Color::from_hex({color_b:?}) }}"
        ));
    }
    if let Some(ref tr) = s.transition {
        fields.push(format!("transition: {}", gen_transition_rust(tr)));
    }
    if let Some(ref fd) = s.flex_direction {
        fields.push(format!("flex_direction: {}", gen_flex_direction(fd)));
    }
    if let Some(ref fb) = s.flex_basis {
        fields.push(format!("flex_basis: {}", gen_dimension(fb)));
    }
    if let Some(order) = s.order {
        fields.push(format!("order: {order}"));
    }
    if let Some(ref als) = s.align_self {
        fields.push(format!("align_self: {}", gen_align_self(als)));
    }
    if let Some(ref alc) = s.align_content {
        fields.push(format!("align_content: {}", gen_align_content(alc)));
    }
    if let Some(ref mw) = s.max_width {
        fields.push(format!("max_width: {}", gen_dimension(mw)));
    }
    if let Some(ref mh) = s.max_height {
        fields.push(format!("max_height: {}", gen_dimension(mh)));
    }
    if let Some(ref ff) = s.font_family {
        fields.push(format!("font_family: Some({ff:?}.to_string())"));
    }
    if let Some(ref fs) = s.font_style {
        fields.push(format!("font_style: {}", gen_font_style(fs)));
    }
    if let Some(ls) = s.letter_spacing {
        fields.push(format!("letter_spacing: {ls}_f32"));
    }
    if let Some(ref td) = s.text_decoration {
        fields.push(format!("text_decoration: {}", gen_text_decoration(td)));
    }
    if let Some(ref to) = s.text_overflow {
        fields.push(format!("text_overflow: {}", gen_text_overflow(to)));
    }
    if let Some(ref wb) = s.word_break {
        fields.push(format!("word_break: {}", gen_word_break(wb)));
    }
    if let Some(ref vis) = s.visibility {
        fields.push(format!("visibility: {}", gen_visibility(vis)));
    }
    if let Some(ref cur) = s.cursor {
        fields.push(format!("cursor: {}", gen_cursor(cur)));
    }
    if let Some(ref pe) = s.pointer_events {
        fields.push(format!("pointer_events: {}", gen_pointer_events(pe)));
    }
    if let Some(ref us) = s.user_select {
        fields.push(format!("user_select: {}", gen_user_select(us)));
    }
    if let Some(ow) = s.outline_width {
        fields.push(format!("outline_width: {ow}_f32"));
    }
    if let Some(ref oc) = s.outline_color {
        fields.push(format!("outline_color: Color::from_hex({oc:?})"));
    }
    if let Some(ref os) = s.outline_style {
        fields.push(format!("outline_style: {}", gen_outline_style(os)));
    }
    if let Some(ref tr) = s.transform {
        fields.push(format!("transform: {}", gen_transform_rust(tr)));
    }
    if let Some(ref bs) = s.box_shadow {
        if let Some(code) = gen_box_shadow_rust(bs) {
            fields.push(code);
        }
    }
    if let Some(ref anim) = s.animation {
        if let Some(code) = gen_animation_rust(anim) {
            fields.push(code);
        }
    }
    if let Some(ref c) = s.contain {
        fields.push(format!("contain: {}", gen_contain(c)));
    }
    if let Some(ref wc) = s.will_change {
        fields.push(format!("will_change: {}", gen_will_change(wc)));
    }
    if let Some(ref f) = s.filter {
        fields.push(format!("filter: Some({f:?}.to_string())"));
    }

    if fields.is_empty() {
        "Style::default()".to_string()
    } else {
        let joined = fields.join(&format!(",\n{indent}    "));
        format!("Style {{\n{indent}    {joined},\n{indent}    ..Style::default()\n{indent}}}")
    }
}

fn gen_flex_direction(s: &str) -> String {
    match s {
        "row" => "FlexDirection::Row".to_string(),
        "row-reverse" | "rowReverse" => "FlexDirection::RowReverse".to_string(),
        "column-reverse" | "columnReverse" => "FlexDirection::ColumnReverse".to_string(),
        _ => "FlexDirection::Column".to_string(),
    }
}

fn gen_align_self(s: &str) -> String {
    match s {
        "center" => "AlignSelf::Center".to_string(),
        "flex-start" | "flexStart" => "AlignSelf::FlexStart".to_string(),
        "flex-end" | "flexEnd" => "AlignSelf::FlexEnd".to_string(),
        "baseline" => "AlignSelf::Baseline".to_string(),
        "stretch" => "AlignSelf::Stretch".to_string(),
        _ => "AlignSelf::Auto".to_string(),
    }
}

fn gen_align_content(s: &str) -> String {
    match s {
        "center" => "AlignContent::Center".to_string(),
        "flex-start" | "flexStart" => "AlignContent::FlexStart".to_string(),
        "flex-end" | "flexEnd" => "AlignContent::FlexEnd".to_string(),
        "space-between" | "spaceBetween" => "AlignContent::SpaceBetween".to_string(),
        "space-around" | "spaceAround" => "AlignContent::SpaceAround".to_string(),
        _ => "AlignContent::Stretch".to_string(),
    }
}

fn gen_font_style(s: &str) -> String {
    match s {
        "italic" => "FontStyle::Italic".to_string(),
        "oblique" => "FontStyle::Oblique".to_string(),
        _ => "FontStyle::Normal".to_string(),
    }
}

fn gen_text_decoration(s: &str) -> String {
    if s.contains("underline") {
        "TextDecoration::Underline".to_string()
    } else if s.contains("line-through") {
        "TextDecoration::LineThrough".to_string()
    } else {
        "TextDecoration::None".to_string()
    }
}

fn gen_text_overflow(s: &str) -> String {
    match s {
        "ellipsis" => "TextOverflow::Ellipsis".to_string(),
        _ => "TextOverflow::Clip".to_string(),
    }
}

fn gen_word_break(s: &str) -> String {
    match s {
        "break-all" | "breakAll" => "WordBreak::BreakAll".to_string(),
        "keep-all" | "keepAll" => "WordBreak::KeepAll".to_string(),
        _ => "WordBreak::Normal".to_string(),
    }
}

fn gen_visibility(s: &str) -> String {
    match s {
        "hidden" => "Visibility::Hidden".to_string(),
        "collapse" => "Visibility::Collapse".to_string(),
        _ => "Visibility::Visible".to_string(),
    }
}

fn gen_cursor(s: &str) -> String {
    match s {
        "pointer" => "Cursor::Pointer".to_string(),
        "text" => "Cursor::Text".to_string(),
        "not-allowed" | "notAllowed" => "Cursor::NotAllowed".to_string(),
        "grab" => "Cursor::Grab".to_string(),
        _ => "Cursor::Default".to_string(),
    }
}

fn gen_pointer_events(s: &str) -> String {
    match s {
        "none" => "PointerEvents::None".to_string(),
        _ => "PointerEvents::Auto".to_string(),
    }
}

fn gen_user_select(s: &str) -> String {
    match s {
        "none" => "UserSelect::None".to_string(),
        "text" => "UserSelect::Text".to_string(),
        "all" => "UserSelect::All".to_string(),
        _ => "UserSelect::Auto".to_string(),
    }
}

fn gen_outline_style(s: &str) -> String {
    match s {
        "solid" => "OutlineStyle::Solid".to_string(),
        "dashed" => "OutlineStyle::Dashed".to_string(),
        "dotted" => "OutlineStyle::Dotted".to_string(),
        _ => "OutlineStyle::None".to_string(),
    }
}

fn gen_transform_rust(value: &str) -> String {
    let t = parse_transform(value);
    format!(
        "Transform2D {{ translate_x: {}_f32, translate_y: {}_f32, scale_x: {}_f32, scale_y: {}_f32, rotate_deg: {}_f32 }}",
        t.translate_x, t.translate_y, t.scale_x, t.scale_y, t.rotate_deg
    )
}

fn gen_box_shadow_rust(value: &str) -> Option<String> {
    let s = parse_box_shadow(value)?;
    Some(format!(
        "box_shadow: Some(BoxShadow::new({}_f32, {}_f32, {}_f32, {}_f32, Color::from_hex({:?})))",
        s.offset_x, s.offset_y, s.blur, s.spread, s.color
    ))
}

fn gen_animation_rust(value: &str) -> Option<String> {
    let a = parse_animation(value)?;
    let easing = match a.easing.as_str() {
        "linear" => "Easing::Linear",
        "ease-in" => "Easing::EaseIn",
        "ease-out" => "Easing::EaseOut",
        "ease-in-out" => "Easing::EaseInOut",
        _ => "Easing::Ease",
    };
    Some(format!(
        "animation: Some(Animation {{ name: {:?}.to_string(), duration_ms: {}, easing: {easing}, delay_ms: {}, iteration_count: AnimationIterationCount::Once, direction: AnimationDirection::Normal, fill_mode: AnimationFillMode::None }})",
        a.name, a.duration_ms, a.delay_ms
    ))
}

fn gen_contain(s: &str) -> String {
    match s.trim().to_lowercase().as_str() {
        "strict" => "Contain::Strict".to_string(),
        "content" => "Contain::Content".to_string(),
        "layout" => "Contain::Layout".to_string(),
        "size" => "Contain::Size".to_string(),
        _ => "Contain::None".to_string(),
    }
}

fn gen_will_change(s: &str) -> String {
    let wc = w3cos_std::style::WillChange::from_css(s);
    format!(
        "WillChange {{ transform: {}, opacity: {}, filter: {}, scroll_position: {} }}",
        wc.transform, wc.opacity, wc.filter, wc.scroll_position
    )
}

fn gen_dimension(val: &str) -> String {
    let val = val.trim();
    if let Some(px) = css_values::css_parse_calc_px(val) {
        return format!("Dimension::Px({px}_f32)");
    }
    let suffixes: &[(&str, &str)] = &[
        ("%", "Dimension::Percent"),
        ("px", "Dimension::Px"),
        ("rem", "Dimension::Rem"),
        ("em", "Dimension::Em"),
        ("vw", "Dimension::Vw"),
        ("vh", "Dimension::Vh"),
    ];
    for &(suffix, variant) in suffixes {
        if let Some(num_str) = val.strip_suffix(suffix)
            && let Ok(n) = num_str.trim().parse::<f32>()
        {
            return format!("{variant}({n}_f32)");
        }
    }
    if val == "auto" {
        return "Dimension::Auto".to_string();
    }
    if let Ok(n) = val.parse::<f32>() {
        return format!("Dimension::Px({n}_f32)");
    }
    "Dimension::Auto".to_string()
}

// ---------------------------------------------------------------------------
// DOM codegen backend — generates document.createElement / appendChild calls
// ---------------------------------------------------------------------------

/// Generate Rust code that builds a DOM tree using w3cos_runtime::dom APIs.
pub fn generate_dom(tree: &AppTree) -> Result<String> {
    let is_reactive = !tree.signals.is_empty();
    let signal_names: Vec<&str> = tree.signals.iter().map(|s| s.name.as_str()).collect();
    let mut body = String::new();

    if is_reactive {
        for (i, sig) in tree.signals.iter().enumerate() {
            body.push_str(&format!(
                "    let _ = {};\n    let {} = w3cos_runtime::state::get_signal({});\n",
                sig.initial.rust_initializer(),
                sig.name,
                i
            ));
        }
        body.push('\n');
    }

    let mut counter = 0;
    let root_var = gen_dom_node(&tree.root, &mut body, &mut counter, 1, &signal_names);
    body.push_str(&format!(
        "\n    let body = w3cos_runtime::dom::body_id();\n"
    ));
    body.push_str(&format!(
        "    w3cos_runtime::dom::append_child(body, {root_var});\n"
    ));

    let imports = if is_reactive {
        "use w3cos_std::EventAction;\n"
    } else {
        ""
    };

    Ok(format!(
        r#"//! Auto-generated by w3cos compiler — do not edit (DOM mode).
{imports}
fn main() {{
    w3cos_runtime::run_app_dom(setup).expect("W3C OS app crashed");
}}

fn setup() {{
{body}}}
"#
    ))
}

fn gen_dom_node(
    node: &Node,
    out: &mut String,
    counter: &mut usize,
    depth: usize,
    signal_names: &[&str],
) -> String {
    let indent = "    ".repeat(depth);
    let var = format!("n{}", *counter);
    *counter += 1;

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            let text_expr = gen_text_expr(text, signal_names);
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_text_node(&{text_expr});\n"
            ));
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"button\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_text_content({var}, {lbl:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::add_event_listener({var}, \"click\", {action});\n"
                ));
            }
        }
        NodeKind::Image(src) => {
            let src_val = node.src.as_deref().unwrap_or(src.as_str());
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"img\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"src\", {src_val:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
        }
        NodeKind::TextInput => {
            let placeholder = node.placeholder.as_deref().unwrap_or("Enter text");
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element(\"input\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"type\", \"text\");\n"
            ));
            out.push_str(&format!(
                "{indent}w3cos_runtime::dom::set_attribute({var}, \"placeholder\", {placeholder:?});\n"
            ));
            gen_dom_style_calls(&node.style, &var, out, &indent);
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let tag = "div";
            out.push_str(&format!(
                "{indent}let {var} = w3cos_runtime::dom::create_element({tag:?});\n"
            ));

            // Set flex-direction for Row
            if matches!(node.kind, NodeKind::Row) {
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::set_style_property({var}, \"flex-direction\", \"row\");\n"
                ));
            }

            gen_dom_style_calls(&node.style, &var, out, &indent);

            if let Some(ref action_str) = node.on_click {
                let action = gen_event_action(action_str, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::add_event_listener({var}, \"click\", {action});\n"
                ));
            }

            for child in &node.children {
                let child_var = gen_dom_node(child, out, counter, depth, signal_names);
                out.push_str(&format!(
                    "{indent}w3cos_runtime::dom::append_child({var}, {child_var});\n"
                ));
            }
        }
    }

    var
}

fn gen_dom_style_calls(style: &StyleDecl, var: &str, out: &mut String, indent: &str) {
    let sp = |prop: &str, val: &str| {
        format!("{indent}w3cos_runtime::dom::set_style_property({var}, {prop:?}, {val:?});\n")
    };

    if let Some(gap) = style.gap {
        out.push_str(&sp("gap", &format!("{gap}px")));
    }
    if let Some(p) = style.padding {
        let css = match p {
            Spacing::Px(v) => format!("{v}px"),
            Spacing::SafeAreaInset(SafeAreaEdge::Top) => "env(safe-area-inset-top)".to_string(),
            Spacing::SafeAreaInset(SafeAreaEdge::Right) => "env(safe-area-inset-right)".to_string(),
            Spacing::SafeAreaInset(SafeAreaEdge::Bottom) => {
                "env(safe-area-inset-bottom)".to_string()
            }
            Spacing::SafeAreaInset(SafeAreaEdge::Left) => "env(safe-area-inset-left)".to_string(),
            Spacing::KeyboardInsetHeight => {
                "env(keyboard-inset-height, var(--w3cos-keyboard-inset-height, 0px))".to_string()
            }
            Spacing::Composite {
                px,
                safe_area,
                keyboard_inset,
            } => {
                let mut terms: Vec<String> = Vec::new();
                if px.abs() > f32::EPSILON {
                    terms.push(format!("{px}px"));
                }
                if let Some(e) = safe_area {
                    terms.push(match e {
                        SafeAreaEdge::Top => "env(safe-area-inset-top)".to_string(),
                        SafeAreaEdge::Right => "env(safe-area-inset-right)".to_string(),
                        SafeAreaEdge::Bottom => "env(safe-area-inset-bottom)".to_string(),
                        SafeAreaEdge::Left => "env(safe-area-inset-left)".to_string(),
                    });
                }
                if keyboard_inset {
                    terms.push(
                        "env(keyboard-inset-height, var(--w3cos-keyboard-inset-height, 0px))"
                            .to_string(),
                    );
                }
                match terms.len() {
                    0 => "0px".to_string(),
                    1 => terms[0].clone(),
                    _ => format!("calc({})", terms.join(" + ")),
                }
            }
        };
        out.push_str(&sp("padding", &css));
    }
    if let Some(fs) = style.font_size {
        out.push_str(&sp("font-size", &format!("{fs}px")));
    }
    if let Some(fw) = style.font_weight {
        out.push_str(&sp("font-weight", &fw.to_string()));
    }
    if let Some(ref c) = style.color {
        out.push_str(&sp("color", c));
    }
    if let Some(ref bg) = style.background {
        out.push_str(&sp("background-color", bg));
    }
    if let Some(br) = style.border_radius {
        out.push_str(&sp("border-radius", &format!("{br}px")));
    }
    if let Some(bw) = style.border_width {
        out.push_str(&sp("border-width", &format!("{bw}px")));
    }
    if let Some(ref bc) = style.border_color {
        out.push_str(&sp("border-color", bc));
    }
    if let Some(ref ai) = style.align_items {
        out.push_str(&sp("align-items", ai));
    }
    if let Some(ref jc) = style.justify_content {
        out.push_str(&sp("justify-content", jc));
    }
    if let Some(ref w) = style.width {
        out.push_str(&sp("width", w));
    }
    if let Some(ref h) = style.height {
        out.push_str(&sp("height", h));
    }
    if let Some(fg) = style.flex_grow {
        out.push_str(&sp("flex-grow", &fg.to_string()));
    }
    if let Some(ref d) = style.display {
        out.push_str(&sp("display", d));
    }
    if let Some(ref p) = style.position {
        out.push_str(&sp("position", p));
    }
    if let Some(ref ov) = style.overflow {
        out.push_str(&sp("overflow", ov));
    }
    if let Some(ref t) = style.top {
        out.push_str(&sp("top", t));
    }
    if let Some(ref r) = style.right {
        out.push_str(&sp("right", r));
    }
    if let Some(ref b) = style.bottom {
        out.push_str(&sp("bottom", b));
    }
    if let Some(ref l) = style.left {
        out.push_str(&sp("left", l));
    }
    if let Some(zi) = style.z_index {
        out.push_str(&sp("z-index", &zi.to_string()));
    }
}

#[cfg(test)]
mod tests {
    use crate::css_parser;
    use crate::parser::{AppTree, Node, NodeKind, StyleDecl};

    use super::*;

    fn empty_sheet() -> Stylesheet {
        css_parser::Stylesheet::empty()
    }

    fn test_node(kind: NodeKind, style: StyleDecl) -> Node {
        Node {
            kind,
            style,
            children: vec![],
            text: None,
            label: None,
            on_click: None,
            src: None,
            placeholder: None,
            class_name: None,
            show_when: None,
            repeat: None,
            sticky_counter: None,
        }
    }

    fn test_tree(root: Node) -> AppTree {
        AppTree {
            root,
            signals: vec![],
            css_imports: vec![],
        }
    }

    #[test]
    fn codegen_cargo_toml_devtools_feature() {
        let opts = CompileOptions { devtools: true };
        let toml = generate_cargo_toml(std::path::Path::new("."), &opts).unwrap();
        assert!(
            toml.contains(r#"features = ["devtools"]"#),
            "devtools feature missing: {toml}"
        );
    }

    #[test]
    fn codegen_text_produces_component_text() {
        let mut node = test_node(NodeKind::Text("hello".into()), StyleDecl::default());
        node.text = Some("hello".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::text(\"hello\""));
        assert!(rust.contains("fn build_ui()"));
        assert!(rust.contains("w3cos_runtime::run_app"));
    }

    #[test]
    fn codegen_button_produces_component_button() {
        let mut node = test_node(NodeKind::Button("click me".into()), StyleDecl::default());
        node.label = Some("click me".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::button(\"click me\""));
    }

    #[test]
    fn codegen_column_with_children() {
        let mut root = test_node(NodeKind::Column, StyleDecl::default());
        let mut a = test_node(NodeKind::Text("a".into()), StyleDecl::default());
        a.text = Some("a".into());
        let mut b = test_node(NodeKind::Text("b".into()), StyleDecl::default());
        b.text = Some("b".into());
        root.children = vec![a, b];
        let rust = generate(&test_tree(root), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::column"));
        assert!(rust.contains("Component::text(\"a\""));
        assert!(rust.contains("Component::text(\"b\""));
        assert!(rust.contains("vec!["));
    }

    #[test]
    fn codegen_virtual_list_keeps_single_template() {
        let mut style = StyleDecl::default();
        style.virtual_count = Some(1_000_000);
        style.estimated_item_height = Some(56.0);
        style.virtual_overscan = Some(180.0);
        let mut root = test_node(NodeKind::Column, style);
        let mut template = test_node(NodeKind::Text("row-{index}".into()), StyleDecl::default());
        template.text = Some("row-{index}".into());
        root.children = vec![template];

        let rust = generate(&test_tree(root), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::virtual_list(1000000, 56.0, 180.0"));
        assert_eq!(rust.matches("row-{index}").count(), 1);
    }

    #[test]
    fn codegen_text_input_produces_component_text_input() {
        let mut node = test_node(NodeKind::TextInput, StyleDecl::default());
        node.placeholder = Some("Enter name".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::text_input"));
        assert!(rust.contains("\"Enter name\""));
    }

    #[test]
    fn codegen_row_with_style() {
        let mut style = StyleDecl::default();
        style.gap = Some(10.0);
        let rust = generate(&test_tree(test_node(NodeKind::Row, style)), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::row"));
        assert!(rust.contains("gap: 10_f32"));
    }

    #[test]
    fn codegen_style_color_and_background() {
        let mut style = StyleDecl::default();
        style.color = Some("#fff".into());
        style.background = Some("#e94560".into());
        let mut node = test_node(NodeKind::Text("styled".into()), style);
        node.text = Some("styled".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Color::from_hex(\"#fff\")"));
        assert!(rust.contains("Color::from_hex(\"#e94560\")"));
    }

    #[test]
    fn codegen_image_produces_component_image() {
        let mut node = test_node(NodeKind::Image("path.png".into()), StyleDecl::default());
        node.src = Some("path.png".into());
        let rust = generate(&test_tree(node), &empty_sheet()).unwrap();
        assert!(rust.contains("Component::image(\"path.png\""));
    }

    #[test]
    fn codegen_with_css_stylesheet() {
        let css = ".title { font-size: 24; color: #e94560; }";
        let sheet = css_parser::parse_css(css);
        let mut node = test_node(NodeKind::Text("Hello".into()), StyleDecl::default());
        node.text = Some("Hello".into());
        node.class_name = Some("title".into());
        let rust = generate(&test_tree(node), &sheet).unwrap();
        assert!(rust.contains("font_size: 24_f32"));
        assert!(rust.contains("Color::from_hex(\"#e94560\")"));
    }

    #[test]
    fn codegen_css_overridden_by_inline() {
        let css = ".title { color: red; font-size: 24; }";
        let sheet = css_parser::parse_css(css);
        let mut style = StyleDecl::default();
        style.color = Some("#fff".into());
        let mut node = test_node(NodeKind::Text("Hello".into()), style);
        node.text = Some("Hello".into());
        node.class_name = Some("title".into());
        let rust = generate(&test_tree(node), &sheet).unwrap();
        assert!(rust.contains("Color::from_hex(\"#fff\")"));
        assert!(rust.contains("font_size: 24_f32"));
    }
}
