//! ESM bundle -> Rust module skeleton code generation.
//!
//! Takes a flattened `EsmBundle` (see `esm_resolver`) and emits a Rust module
//! skeleton: each ESM module becomes a `mod`, each top-level `class` becomes a
//! `struct` + `impl`, each top-level `function` becomes an `fn`. Cross-module
//! bindings are emitted as `use` re-exports so the bundled names line up.
//!
//! `generate_skeleton` produces `todo!()` placeholders.
//! `generate_with_bodies` reads source files and lowers JS function bodies to Rust.

use crate::esm_lowering::{LowerCtx, sanitize_ident};
use crate::esm_resolver::{BundledModule, EsmBundle, SymbolKind};
use std::collections::HashSet;
use std::path::Path;
use swc_common::{FileName, SourceMap, sync::Lrc};
use swc_ecma_ast::*;
use swc_ecma_parser::{EsSyntax, Parser, StringInput, Syntax, lexer::Lexer};

/// Generate a Rust module skeleton from a fully built ESM bundle.
pub fn generate_skeleton(bundle: &EsmBundle) -> String {
    let mut out = String::new();
    out.push_str("// Generated by w3cos esm_codegen (structural skeleton)\n");
    out.push_str(&format!("// bundle entry: {}\n", bundle.entry.display()));
    out.push_str(&format!(
        "// modules: {}, symbols: {}\n\n",
        bundle.modules.len(),
        bundle.symbols.len()
    ));

    for module in &bundle.modules {
        out.push_str(&generate_module(bundle, module));
        out.push('\n');
    }

    out
}

fn generate_module(bundle: &EsmBundle, module: &BundledModule) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "/// ESM module: {}\nmod {} {{\n",
        module.path.display(),
        module.namespace
    ));
    for (local, host_path) in &module.host_imports {
        out.push_str(&format!(
            "    pub fn {}(__args: Vec<w3cos_core::Value>) -> w3cos_core::Value {{ w3cos_react_compat::aot::call_host({host_path:?}, __args) }}\n",
            sanitize_ident(local),
        ));
    }

    // Emit `use` aliases for imported bindings so local names resolve to the
    // bundled definition living in another module's namespace.
    for (local, bundled) in &module.local_to_bundled {
        // Only emit a use for cross-module references (bundled name not owned here).
        let owned = bundle
            .symbols
            .iter()
            .any(|s| s.bundled_name == *bundled && s.module == module.path);
        if owned {
            continue;
        }
        if let Some(owner) = bundle.modules.iter().find(|m| {
            bundle
                .symbols
                .iter()
                .any(|s| s.bundled_name == *bundled && s.module == m.path)
        }) {
            out.push_str(&format!(
                "    pub use super::{}::{} as {};\n",
                owner.namespace,
                bundled,
                sanitize_ident(local)
            ));
        }
    }

    // Emit the module's own definitions.
    for sym in bundle.symbols.iter().filter(|s| s.module == module.path) {
        match sym.kind {
            SymbolKind::Class => {
                out.push_str(&format!(
                    "\n    /// class {} (from ESM)\n    pub struct {} {{}}\n",
                    sym.original_name, sym.bundled_name
                ));
                out.push_str(&format!(
                    "    impl {} {{\n        pub fn new() -> Self {{ Self {{}} }}\n    }}\n",
                    sym.bundled_name
                ));
                // Alias so the original name is usable within this module.
                let alias = sanitize_ident(&sym.original_name);
                if alias != sym.bundled_name {
                    out.push_str(&format!(
                        "    pub use self::{} as {};\n",
                        sym.bundled_name, alias
                    ));
                }
            }
            SymbolKind::Function => {
                out.push_str(&format!(
                    "\n    /// function {} (from ESM)\n    pub fn {}() {{ todo!(\"lower ESM body: {}\") }}\n",
                    sym.original_name, sym.bundled_name, sym.original_name
                ));
                let alias = sanitize_ident(&sym.original_name);
                if alias != sym.bundled_name {
                    out.push_str(&format!(
                        "    pub use self::{} as {};\n",
                        sym.bundled_name, alias
                    ));
                }
            }
            SymbolKind::Variable => {
                out.push_str(&format!(
                    "\n    // variable {} (from ESM) — lowering pending\n",
                    sym.original_name
                ));
            }
        }
    }

    out.push_str("}\n");
    out
}

/// Generate Rust module code with real function bodies lowered from JS AST.
pub fn generate_with_bodies(bundle: &EsmBundle) -> String {
    let mut out = String::new();
    out.push_str("// Generated by w3cos esm_codegen (with lowered bodies)\n");
    out.push_str(&format!("// bundle entry: {}\n", bundle.entry.display()));
    out.push_str(&format!(
        "// modules: {}, symbols: {}\n\n",
        bundle.modules.len(),
        bundle.symbols.len()
    ));

    for module in &bundle.modules {
        out.push_str(&generate_module_with_bodies(bundle, module));
        out.push('\n');
    }

    if let Some(symbol) = bundle
        .symbols
        .iter()
        .find(|symbol| symbol.module == bundle.entry && symbol.original_name == "main")
        && let Some(module) = bundle
            .modules
            .iter()
            .find(|module| module.path == bundle.entry)
    {
        out.push_str(&format!(
            "pub fn run_entry() -> w3cos_core::Value {{ {}::{}(vec![]) }}\n",
            module.namespace, symbol.bundled_name
        ));
    } else {
        out.push_str("pub fn run_entry() -> w3cos_core::Value { w3cos_core::Value::Undefined }\n");
    }

    out
}

fn generate_module_with_bodies(bundle: &EsmBundle, module: &BundledModule) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "/// ESM module: {}\nmod {} {{\n",
        module.path.display(),
        module.namespace
    ));
    out.push_str(
        "    #[allow(unused_imports)]\n    use w3cos_core::{Array, Error, ErrorValue, Map, Math, Object, RangeError, ResizeObserver, console, document, parseFloat, parseInt};\n",
    );
    for (local, host_path) in &module.host_imports {
        out.push_str(&format!(
            "    pub fn {}(__args: Vec<w3cos_core::Value>) -> w3cos_core::Value {{ w3cos_react_compat::aot::call_host({host_path:?}, __args) }}\n",
            sanitize_ident(local),
        ));
    }

    // Emit cross-module use aliases (same as skeleton).
    for (local, bundled) in &module.local_to_bundled {
        let owned = bundle
            .symbols
            .iter()
            .any(|s| s.bundled_name == *bundled && s.module == module.path);
        if owned {
            continue;
        }
        if let Some(owner) = bundle.modules.iter().find(|m| {
            bundle
                .symbols
                .iter()
                .any(|s| s.bundled_name == *bundled && s.module == m.path)
        }) {
            out.push_str(&format!(
                "    pub use super::{}::{} as {};\n",
                owner.namespace,
                bundled,
                sanitize_ident(local)
            ));
        }
    }

    // Parse the module's source to get function bodies.
    let functions = parse_module_functions(&module.path);
    let value_bindings: HashSet<String> = functions
        .iter()
        .filter_map(|item| match item {
            TopLevelItem::Variable { name, .. } => Some(name.clone()),
            _ => None,
        })
        .collect();

    // Emit definitions with bodies.
    for sym in bundle.symbols.iter().filter(|s| s.module == module.path) {
        match sym.kind {
            SymbolKind::Class => {
                out.push_str(&format!(
                    "\n    /// class {} (from ESM)\n    pub struct {} {{}}\n",
                    sym.original_name, sym.bundled_name
                ));
                // Emit methods from the class body.
                let methods = find_class_methods(&functions, &sym.original_name);
                out.push_str(&format!("    impl {} {{\n", sym.bundled_name));
                out.push_str("        pub fn new() -> Self { Self {} }\n");
                for (method_name, body_code) in &methods {
                    let safe_method = sanitize_ident(method_name);
                    out.push_str(&format!(
                        "        pub fn {safe_method}(&self) {{\n{body_code}\n        }}\n"
                    ));
                }
                out.push_str("    }\n");
                let alias = sanitize_ident(&sym.original_name);
                if alias != sym.bundled_name {
                    out.push_str(&format!("    pub type {} = {};\n", alias, sym.bundled_name));
                }
            }
            SymbolKind::Function => {
                let renames = lowering_names(module);
                let (params, body) =
                    find_function(&functions, &sym.original_name, &renames, &value_bindings)
                        .unwrap_or_else(|| {
                            (
                                Vec::new(),
                                format!("        todo!(\"body not found: {}\")", sym.original_name),
                            )
                        });
                let bindings = lower_dynamic_params(&params, &renames);
                let body = format!("{bindings}{body}");
                out.push_str(&format!(
                    "\n    /// function {} (from ESM)\n    pub fn {}(__args: Vec<w3cos_core::Value>) -> w3cos_core::Value {{\n{}\n        w3cos_core::Value::Undefined\n    }}\n",
                    sym.original_name, sym.bundled_name, body
                ));
                let alias = sanitize_ident(&sym.original_name);
                if alias != sym.bundled_name {
                    out.push_str(&format!(
                        "    pub use self::{} as {};\n",
                        sym.bundled_name, alias
                    ));
                }
            }
            SymbolKind::Variable => {
                let renames = lowering_names(module);
                if let Some((params, body)) =
                    find_function(&functions, &sym.original_name, &renames, &value_bindings)
                {
                    let bindings = lower_dynamic_params(&params, &renames);
                    let body = format!("{bindings}{body}");
                    out.push_str(&format!(
                        "\n    /// function-valued variable {} (from ESM)\n    pub fn {}(__args: Vec<w3cos_core::Value>) -> w3cos_core::Value {{\n{}\n        w3cos_core::Value::Undefined\n    }}\n",
                        sym.original_name, sym.bundled_name, body
                    ));
                    let alias = sanitize_ident(&sym.original_name);
                    if alias != sym.bundled_name {
                        out.push_str(&format!(
                            "    pub use self::{} as {};\n",
                            sym.bundled_name, alias
                        ));
                    }
                } else if let Some(target) = find_alias(&functions, &sym.original_name) {
                    out.push_str(&format!(
                        "\n    pub use self::{} as {};\n",
                        sanitize_ident(target),
                        sym.bundled_name
                    ));
                    let alias = sanitize_ident(&sym.original_name);
                    if alias != sym.bundled_name {
                        out.push_str(&format!(
                            "    pub use self::{} as {};\n",
                            sym.bundled_name, alias
                        ));
                    }
                } else if let Some(initializer) = find_variable(&functions, &sym.original_name) {
                    let ctx = LowerCtx::new_dynamic_with_bindings(
                        renames.clone(),
                        value_bindings.clone(),
                    );
                    let initializer = ctx.lower_expr(initializer);
                    out.push_str(&format!(
                        "\n    std::thread_local! {{ static {}_CELL: std::cell::RefCell<Option<w3cos_core::Value>> = const {{ std::cell::RefCell::new(None) }}; }}\n    pub fn {}_get() -> w3cos_core::Value {{ {}_CELL.with(|cell| {{ if let Some(value) = cell.borrow().as_ref() {{ return value.clone(); }} let value = {initializer}; *cell.borrow_mut() = Some(value.clone()); value }}) }}\n    pub fn {}_set(value: w3cos_core::Value) -> w3cos_core::Value {{ {}_CELL.with(|cell| *cell.borrow_mut() = Some(value.clone())); value }}\n",
                        sym.bundled_name,
                        sym.bundled_name,
                        sym.bundled_name,
                        sym.bundled_name,
                        sym.bundled_name,
                    ));
                    let alias = sanitize_ident(&sym.original_name);
                    if alias != sym.bundled_name {
                        out.push_str(&format!(
                            "    pub use self::{}_get as {};\n",
                            sym.bundled_name, alias
                        ));
                    }
                } else {
                    out.push_str(&format!(
                        "\n    // variable {} (from ESM) — value lowering pending\n",
                        sym.original_name
                    ));
                }
            }
        }
    }

    out.push_str("}\n");
    out
}

fn lowering_names(module: &BundledModule) -> Vec<(String, String)> {
    let mut names = module.local_to_bundled.clone();
    names.extend(
        module
            .host_imports
            .iter()
            .map(|(local, _)| (local.clone(), sanitize_ident(local))),
    );
    names
}

/// Parsed function/class from a module source.
enum TopLevelItem {
    Function {
        name: String,
        params: Vec<Pat>,
        body: Vec<Stmt>,
    },
    Class {
        name: String,
        methods: Vec<(String, Vec<Stmt>)>,
    },
    Variable {
        name: String,
        initializer: Box<Expr>,
    },
    Alias {
        name: String,
        target: String,
    },
}

fn parse_module_functions(path: &Path) -> Vec<TopLevelItem> {
    let source = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => return Vec::new(),
    };

    let cm: Lrc<SourceMap> = Default::default();
    let fm = cm.new_source_file(Lrc::new(FileName::Real(path.to_path_buf())), source);
    let syntax = if path.extension().map_or(false, |e| e == "ts" || e == "tsx") {
        Syntax::Typescript(Default::default())
    } else {
        Syntax::Es(EsSyntax {
            decorators: true,
            ..Default::default()
        })
    };
    let lexer = Lexer::new(syntax, Default::default(), StringInput::from(&*fm), None);
    let mut parser = Parser::new_from(lexer);
    let module = match parser.parse_module() {
        Ok(m) => m,
        Err(_) => return Vec::new(),
    };

    let mut items = Vec::new();
    for item in &module.body {
        match item {
            ModuleItem::ModuleDecl(ModuleDecl::ExportDecl(export)) => {
                collect_decl_items(&export.decl, &mut items);
            }
            ModuleItem::Stmt(Stmt::Decl(decl)) => {
                collect_decl_items(decl, &mut items);
            }
            _ => {}
        }
    }
    items
}

fn collect_decl_items(decl: &Decl, items: &mut Vec<TopLevelItem>) {
    match decl {
        Decl::Fn(fn_decl) => {
            let name = fn_decl.ident.sym.to_string();
            let params = fn_decl
                .function
                .params
                .iter()
                .map(|param| param.pat.clone())
                .collect();
            let body = fn_decl
                .function
                .body
                .as_ref()
                .map(|b| b.stmts.clone())
                .unwrap_or_default();
            items.push(TopLevelItem::Function { name, params, body });
        }
        Decl::Class(class_decl) => {
            let name = class_decl.ident.sym.to_string();
            let mut methods = Vec::new();
            for member in &class_decl.class.body {
                if let ClassMember::Method(method) = member {
                    let method_name = match &method.key {
                        PropName::Ident(id) => id.sym.to_string(),
                        _ => continue,
                    };
                    if method_name == "constructor" {
                        continue;
                    }
                    let body = method
                        .function
                        .body
                        .as_ref()
                        .map(|b| b.stmts.clone())
                        .unwrap_or_default();
                    methods.push((method_name, body));
                }
            }
            items.push(TopLevelItem::Class { name, methods });
        }
        Decl::Var(var_decl) => {
            for declarator in &var_decl.decls {
                let Pat::Ident(binding) = &declarator.name else {
                    continue;
                };
                let Some(init) = &declarator.init else {
                    continue;
                };
                let (params, body) = match init.as_ref() {
                    Expr::Arrow(arrow) => {
                        let params = arrow.params.clone();
                        let body = match arrow.body.as_ref() {
                            BlockStmtOrExpr::BlockStmt(block) => block.stmts.clone(),
                            BlockStmtOrExpr::Expr(expr) => vec![Stmt::Return(ReturnStmt {
                                span: arrow.span,
                                arg: Some(expr.clone()),
                            })],
                        };
                        (params, body)
                    }
                    Expr::Fn(function) => {
                        let params = function
                            .function
                            .params
                            .iter()
                            .map(|param| param.pat.clone())
                            .collect();
                        let body = function
                            .function
                            .body
                            .as_ref()
                            .map(|block| block.stmts.clone())
                            .unwrap_or_default();
                        (params, body)
                    }
                    Expr::Ident(target) => {
                        items.push(TopLevelItem::Alias {
                            name: binding.id.sym.to_string(),
                            target: target.sym.to_string(),
                        });
                        continue;
                    }
                    Expr::Cond(condition)
                        if is_typeof_window_test(&condition.test)
                            && matches!(condition.cons.as_ref(), Expr::Ident(_))
                            && matches!(condition.alt.as_ref(), Expr::Ident(_)) =>
                    {
                        let Expr::Ident(target) = condition.alt.as_ref() else {
                            unreachable!()
                        };
                        items.push(TopLevelItem::Alias {
                            name: binding.id.sym.to_string(),
                            target: target.sym.to_string(),
                        });
                        continue;
                    }
                    _ => {
                        items.push(TopLevelItem::Variable {
                            name: binding.id.sym.to_string(),
                            initializer: init.clone(),
                        });
                        continue;
                    }
                };
                items.push(TopLevelItem::Function {
                    name: binding.id.sym.to_string(),
                    params,
                    body,
                });
            }
        }
        _ => {}
    }
}

fn find_function(
    items: &[TopLevelItem],
    name: &str,
    renames: &[(String, String)],
    value_bindings: &HashSet<String>,
) -> Option<(Vec<Pat>, String)> {
    for item in items {
        if let TopLevelItem::Function {
            name: fn_name,
            params,
            body,
        } = item
        {
            if fn_name == name {
                let mut ctx =
                    LowerCtx::new_dynamic_with_bindings(renames.to_vec(), value_bindings.clone());
                ctx.bind_patterns(params);
                return Some((params.clone(), ctx.lower_stmts(body)));
            }
        }
    }
    None
}

fn find_variable<'a>(items: &'a [TopLevelItem], name: &str) -> Option<&'a Expr> {
    items.iter().find_map(|item| match item {
        TopLevelItem::Variable {
            name: variable_name,
            initializer,
        } if variable_name == name => Some(initializer.as_ref()),
        _ => None,
    })
}

fn find_alias<'a>(items: &'a [TopLevelItem], name: &str) -> Option<&'a str> {
    items.iter().find_map(|item| match item {
        TopLevelItem::Alias {
            name: alias_name,
            target,
        } if alias_name == name => Some(target.as_str()),
        _ => None,
    })
}

fn is_typeof_window_test(expression: &Expr) -> bool {
    match expression {
        Expr::Bin(binary) => {
            is_typeof_window_test(&binary.left) || is_typeof_window_test(&binary.right)
        }
        Expr::Unary(unary) if unary.op == UnaryOp::TypeOf => {
            matches!(unary.arg.as_ref(), Expr::Ident(ident) if ident.sym == *"window")
        }
        Expr::Paren(parenthesized) => is_typeof_window_test(&parenthesized.expr),
        _ => false,
    }
}

fn lower_dynamic_params(params: &[Pat], renames: &[(String, String)]) -> String {
    let mut bindings = String::new();
    for (index, pattern) in params.iter().enumerate() {
        let argument =
            format!("__args.get({index}).cloned().unwrap_or(w3cos_core::Value::Undefined)");
        lower_dynamic_pattern(pattern, &argument, &mut bindings, renames, 8);
    }
    bindings
}

fn lower_dynamic_pattern(
    pattern: &Pat,
    source: &str,
    output: &mut String,
    renames: &[(String, String)],
    indent: usize,
) {
    let pad = " ".repeat(indent);
    match pattern {
        Pat::Ident(ident) => {
            output.push_str(&format!(
                "{pad}let mut {} = {source};\n",
                sanitize_ident(&ident.id.sym.to_string())
            ));
        }
        Pat::Object(object) => {
            for property in &object.props {
                match property {
                    ObjectPatProp::Assign(assign) => {
                        let name = sanitize_ident(&assign.key.sym.to_string());
                        let value =
                            format!("{source}.get_property({:?})", assign.key.sym.to_string());
                        if let Some(default) = &assign.value {
                            let ctx = LowerCtx::new_dynamic(renames.to_vec());
                            let fallback = ctx.lower_expr(default);
                            output.push_str(&format!(
                                "{pad}let {name} = {{ let value = {value}; if value.is_undefined() {{ {fallback} }} else {{ value }} }};\n"
                            ));
                        } else {
                            output.push_str(&format!("{pad}let {name} = {value};\n"));
                        }
                    }
                    ObjectPatProp::KeyValue(key_value) => {
                        let key = match &key_value.key {
                            PropName::Ident(ident) => ident.sym.to_string(),
                            PropName::Str(value) => {
                                format!("{:?}", value.value).trim_matches('"').to_string()
                            }
                            PropName::Num(value) => value.value.to_string(),
                            _ => continue,
                        };
                        let nested = format!("{source}.get_property({key:?})");
                        lower_dynamic_pattern(&key_value.value, &nested, output, renames, indent);
                    }
                    ObjectPatProp::Rest(rest) => {
                        lower_dynamic_pattern(&rest.arg, source, output, renames, indent);
                    }
                }
            }
        }
        Pat::Array(array) => {
            for (index, element) in array.elems.iter().enumerate() {
                if let Some(element) = element {
                    let nested = format!("{source}.get_property({:?})", index.to_string());
                    lower_dynamic_pattern(element, &nested, output, renames, indent);
                }
            }
        }
        Pat::Assign(assign) => {
            let ctx = LowerCtx::new_dynamic(renames.to_vec());
            let fallback = ctx.lower_expr(&assign.right);
            let value = format!(
                "{{ let value = {source}; if value.is_undefined() {{ {fallback} }} else {{ value }} }}"
            );
            lower_dynamic_pattern(&assign.left, &value, output, renames, indent);
        }
        Pat::Rest(rest) => lower_dynamic_pattern(&rest.arg, source, output, renames, indent),
        _ => {}
    }
}

fn find_class_methods(items: &[TopLevelItem], class_name: &str) -> Vec<(String, String)> {
    for item in items {
        if let TopLevelItem::Class { name, methods } = item {
            if name == class_name {
                return methods
                    .iter()
                    .map(|(method_name, body)| {
                        let mut ctx = LowerCtx::new(vec![]);
                        let code = ctx.lower_stmts(body);
                        (method_name.clone(), code)
                    })
                    .collect();
            }
        }
    }
    Vec::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::esm_resolver::EsmResolver;
    use std::path::PathBuf;

    fn fixture_root(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(name);
        std::fs::remove_dir_all(&dir).ok();
        dir
    }

    #[test]
    fn generates_rust_skeleton_for_codemirror_like_bundle() {
        let root = fixture_root("w3cos_esm_codegen_skeleton");
        std::fs::create_dir_all(root.join("src")).unwrap();
        std::fs::write(
            root.join("src/app.ts"),
            r#"import { EditorView } from "@codemirror/view";
import { EditorState } from "@codemirror/state";
export function main() {}"#,
        )
        .unwrap();

        let view = root.join("node_modules/@codemirror/view");
        std::fs::create_dir_all(view.join("dist")).unwrap();
        std::fs::write(view.join("package.json"), r#"{"module":"dist/index.js"}"#).unwrap();
        std::fs::write(
            view.join("dist/index.js"),
            r#"import { EditorState } from "@codemirror/state";
export class EditorView {}
export function keymap() {}"#,
        )
        .unwrap();

        let state = root.join("node_modules/@codemirror/state");
        std::fs::create_dir_all(state.join("dist")).unwrap();
        std::fs::write(state.join("package.json"), r#"{"module":"dist/index.js"}"#).unwrap();
        std::fs::write(
            state.join("dist/index.js"),
            r#"export class EditorState {}"#,
        )
        .unwrap();

        let resolver = EsmResolver::new(&root);
        let parsed = resolver
            .parse_graph_from_entry(&root.join("src/app.ts"))
            .unwrap();
        let bundle = EsmBundle::build(&parsed, &resolver, &root.join("src/app.ts"));
        let code = generate_skeleton(&bundle);

        // Each module becomes a mod with its namespace.
        assert!(
            code.contains("mod m0"),
            "should emit namespaced modules: {code}"
        );
        // Classes become structs.
        assert!(
            code.contains("pub struct"),
            "classes should become structs: {code}"
        );
        assert!(
            code.contains("EditorView"),
            "EditorView should appear: {code}"
        );
        assert!(
            code.contains("EditorState"),
            "EditorState should appear: {code}"
        );
        // Functions become fns.
        assert!(
            code.contains("pub fn"),
            "functions should become fns: {code}"
        );
        assert!(code.contains("keymap"), "keymap fn should appear: {code}");
        // Cross-module imports become use re-exports.
        assert!(
            code.contains("pub use super::"),
            "cross-module bindings should re-export: {code}"
        );

        std::fs::remove_dir_all(root).ok();
    }

    #[test]
    fn generated_skeleton_compiles_as_valid_rust() {
        let root = fixture_root("w3cos_esm_codegen_compiles");
        std::fs::create_dir_all(root.join("src")).unwrap();
        std::fs::write(
            root.join("src/app.ts"),
            r#"import { Theme } from "my-lib";
export function boot() {}"#,
        )
        .unwrap();

        let lib = root.join("node_modules/my-lib");
        std::fs::create_dir_all(&lib).unwrap();
        std::fs::write(lib.join("package.json"), r#"{"main":"index.js"}"#).unwrap();
        std::fs::write(
            lib.join("index.js"),
            r#"export class Theme {}
export function makeTheme() {}"#,
        )
        .unwrap();

        let resolver = EsmResolver::new(&root);
        let parsed = resolver
            .parse_graph_from_entry(&root.join("src/app.ts"))
            .unwrap();
        let bundle = EsmBundle::build(&parsed, &resolver, &root.join("src/app.ts"));
        let code = generate_skeleton(&bundle);

        // Write the skeleton to a file and type-check it with rustc.
        let rs_path = root.join("skeleton.rs");
        let wrapper =
            format!("#![allow(dead_code, unused_imports, clippy::all)]\nfn main() {{}}\n{code}");
        std::fs::write(&rs_path, wrapper).unwrap();

        let output = std::process::Command::new("rustc")
            .arg("--edition=2021")
            .arg("--emit=metadata")
            .arg("--crate-type=bin")
            .arg("-o")
            .arg(root.join("skeleton_meta"))
            .arg(&rs_path)
            .output()
            .expect("rustc should be available");

        assert!(
            output.status.success(),
            "generated skeleton should compile.\n--- code ---\n{code}\n--- stderr ---\n{}",
            String::from_utf8_lossy(&output.stderr)
        );

        std::fs::remove_dir_all(root).ok();
    }

    #[test]
    fn generate_with_bodies_lowers_function_code() {
        let root = fixture_root("w3cos_esm_codegen_bodies");
        std::fs::create_dir_all(root.join("src")).unwrap();
        std::fs::write(
            root.join("src/app.ts"),
            r#"import { EditorView } from "@codemirror/view";
export function boot() {
  const view = new EditorView({});
  return view;
}
export const identity = (value) => value;
export const readSize = ({height: h, width: w = 10}) => h + w;"#,
        )
        .unwrap();

        let view = root.join("node_modules/@codemirror/view");
        std::fs::create_dir_all(view.join("dist")).unwrap();
        std::fs::write(view.join("package.json"), r#"{"module":"dist/index.js"}"#).unwrap();
        std::fs::write(
            view.join("dist/index.js"),
            r#"export class EditorView {
  mount() {
    const el = document.createElement("div");
    return el;
  }
}"#,
        )
        .unwrap();

        let resolver = EsmResolver::new(&root);
        let parsed = resolver
            .parse_graph_from_entry(&root.join("src/app.ts"))
            .unwrap();
        let bundle = EsmBundle::build(&parsed, &resolver, &root.join("src/app.ts"));
        let code = generate_with_bodies(&bundle);

        // Function body should be lowered, not todo!()
        assert!(
            code.contains("EditorView::new("),
            "new X() should lower to X::new(): {code}"
        );
        assert!(
            code.contains("return view"),
            "return should be lowered: {code}"
        );
        assert!(
            code.contains("function-valued variable identity")
                && code.contains("let mut value = __args.get(0)"),
            "top-level arrow functions should lower to callable Rust functions: {code}"
        );
        assert!(
            code.contains(
                "get(0).cloned().unwrap_or(w3cos_core::Value::Undefined).get_property(\"height\")"
            ) && code.contains("get_property(\"width\"); if value.is_undefined()"),
            "destructured parameters should bind properties and defaults: {code}"
        );
        // Class method body should be lowered
        assert!(
            code.contains("document.createElement"),
            "method body should be lowered: {code}"
        );
        // Should NOT have todo!() for functions that have bodies
        assert!(
            !code.contains("todo!(\"lower ESM body: boot\")"),
            "boot body should be lowered: {code}"
        );

        std::fs::remove_dir_all(root).ok();
    }
}
