/// General TypeScript → Rust transpiler.
///
/// Uses SWC to parse TypeScript into an AST, then generates equivalent Rust code.
/// Supports: variables, functions, if/else, for/while, arrays, objects,
/// type annotations, console.log, method calls, etc.

use crate::ts_types::{self, RustType};
use anyhow::{Result, anyhow};
use swc_common::{FileName, SourceMap, sync::Lrc};
use swc_ecma_ast::*;
use swc_ecma_parser::{Parser, StringInput, Syntax, TsSyntax};

/// Parse TypeScript source and generate Rust code.
pub fn transpile(source: &str) -> Result<String> {
    let module = parse_ts(source)?;
    let mut ctx = TranspileContext::new();
    ctx.transpile_module(&module)?;
    Ok(ctx.finish())
}

fn parse_ts(source: &str) -> Result<Module> {
    let cm: Lrc<SourceMap> = Default::default();
    let fm = cm.new_source_file(Lrc::new(FileName::Custom("input.ts".into())), source.to_string());

    let mut parser = Parser::new(
        Syntax::Typescript(TsSyntax {
            tsx: true,
            ..Default::default()
        }),
        StringInput::from(&*fm),
        None,
    );

    parser
        .parse_module()
        .map_err(|e| anyhow!("TypeScript parse error: {:?}", e))
}

/// Tracks whether a variable has been mutated (needs `let mut` vs `let`).
#[allow(dead_code)]
struct VarInfo {
    rust_type: RustType,
    mutable: bool,
}

struct TranspileContext {
    output: String,
    indent: usize,
    /// Interface / type alias declarations → struct definitions
    struct_defs: Vec<String>,
    /// Track variables in scope for mutability analysis
    vars: std::collections::HashMap<String, VarInfo>,
    /// Names of all variables that are assigned to (x = ...) after declaration
    mutated_vars: std::collections::HashSet<String>,
    needs_hashmap: bool,
}

impl TranspileContext {
    fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            struct_defs: Vec::new(),
            vars: std::collections::HashMap::new(),
            mutated_vars: std::collections::HashSet::new(),
            needs_hashmap: false,
        }
    }

    fn finish(self) -> String {
        let mut result = String::from("//! Auto-generated by w3cos compiler — do not edit.\n\n");
        if self.needs_hashmap {
            result.push_str("use std::collections::HashMap;\n\n");
        }
        for s in &self.struct_defs {
            result.push_str(s);
            result.push('\n');
        }
        result.push_str(&self.output);
        result
    }

    fn line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn push(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn push_indent(&mut self) {
        self.output.push_str(&"    ".repeat(self.indent));
    }

    fn transpile_module(&mut self, module: &Module) -> Result<()> {
        // First pass: collect mutations to determine which vars need `mut`
        for item in &module.body {
            if let ModuleItem::Stmt(stmt) = item {
                self.collect_mutations(stmt);
            }
        }

        let mut has_main = false;
        let mut top_stmts: Vec<&Stmt> = Vec::new();

        for item in &module.body {
            match item {
                ModuleItem::ModuleDecl(decl) => self.transpile_module_decl(decl)?,
                ModuleItem::Stmt(stmt) => {
                    if is_fn_decl(stmt) {
                        self.transpile_stmt(stmt)?;
                    } else {
                        top_stmts.push(stmt);
                    }
                    if is_main_fn(stmt) {
                        has_main = true;
                    }
                }
            }
        }

        if !top_stmts.is_empty() && !has_main {
            self.line("fn main() {");
            self.indent += 1;
            for stmt in top_stmts {
                self.transpile_stmt(stmt)?;
            }
            self.indent -= 1;
            self.line("}");
        }

        Ok(())
    }

    fn collect_mutations(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Expr(expr_stmt) => self.collect_mutations_expr(&expr_stmt.expr),
            Stmt::Block(block) => {
                for s in &block.stmts {
                    self.collect_mutations(s);
                }
            }
            Stmt::If(if_stmt) => {
                self.collect_mutations(&if_stmt.cons);
                if let Some(alt) = &if_stmt.alt {
                    self.collect_mutations(alt);
                }
            }
            Stmt::For(for_stmt) => {
                if let Some(update) = &for_stmt.update {
                    self.collect_mutations_expr(update);
                }
                self.collect_mutations(&for_stmt.body);
            }
            Stmt::ForIn(fi) => self.collect_mutations(&fi.body),
            Stmt::ForOf(fo) => self.collect_mutations(&fo.body),
            Stmt::While(w) => self.collect_mutations(&w.body),
            _ => {}
        }
    }

    fn collect_mutations_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Assign(assign) => {
                if let Some(name) = pat_target_name(&assign.left) {
                    self.mutated_vars.insert(name);
                }
                self.collect_mutations_expr(&assign.right);
            }
            Expr::Update(update) => {
                if let Expr::Ident(ident) = &*update.arg {
                    self.mutated_vars.insert(ident.sym.to_string());
                }
            }
            Expr::Call(call) => {
                // .push() etc. mutate the callee
                if let Callee::Expr(callee_expr) = &call.callee {
                    if let Expr::Member(member) = &**callee_expr {
                        if let Expr::Ident(obj) = &*member.obj {
                            if let MemberProp::Ident(prop) = &member.prop {
                                let method = prop.sym.to_string();
                                if matches!(
                                    method.as_str(),
                                    "push" | "pop" | "shift" | "unshift" | "splice" | "sort"
                                        | "reverse" | "fill" | "set" | "delete" | "clear"
                                ) {
                                    self.mutated_vars.insert(obj.sym.to_string());
                                }
                            }
                        }
                    }
                }
                for arg in &call.args {
                    self.collect_mutations_expr(&arg.expr);
                }
            }
            Expr::Seq(seq) => {
                for e in &seq.exprs {
                    self.collect_mutations_expr(e);
                }
            }
            Expr::Bin(bin) => {
                self.collect_mutations_expr(&bin.left);
                self.collect_mutations_expr(&bin.right);
            }
            _ => {}
        }
    }

    fn transpile_module_decl(&mut self, decl: &ModuleDecl) -> Result<()> {
        match decl {
            ModuleDecl::Import(_) => Ok(()),
            ModuleDecl::ExportDecl(export) => self.transpile_decl(&export.decl),
            ModuleDecl::ExportDefaultExpr(export) => {
                self.push_indent();
                self.push("pub fn default_export() -> ");
                let ty = ts_types::infer_from_expr(&export.expr);
                self.push(&ty.to_rust_str());
                self.push(" {\n");
                self.indent += 1;
                self.push_indent();
                self.transpile_expr(&export.expr)?;
                self.push("\n");
                self.indent -= 1;
                self.line("}");
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn transpile_stmt(&mut self, stmt: &Stmt) -> Result<()> {
        match stmt {
            Stmt::Decl(decl) => self.transpile_decl(decl),
            Stmt::Expr(expr_stmt) => {
                self.push_indent();
                self.transpile_expr(&expr_stmt.expr)?;
                self.push(";\n");
                Ok(())
            }
            Stmt::Return(ret) => {
                self.push_indent();
                if let Some(arg) = &ret.arg {
                    self.transpile_expr(arg)?;
                }
                self.push("\n");
                Ok(())
            }
            Stmt::If(if_stmt) => self.transpile_if(if_stmt),
            Stmt::For(for_stmt) => self.transpile_for(for_stmt),
            Stmt::ForIn(fi) => self.transpile_for_in(fi),
            Stmt::ForOf(fo) => self.transpile_for_of(fo),
            Stmt::While(w) => self.transpile_while(w),
            Stmt::Block(block) => {
                self.line("{");
                self.indent += 1;
                for s in &block.stmts {
                    self.transpile_stmt(s)?;
                }
                self.indent -= 1;
                self.line("}");
                Ok(())
            }
            Stmt::Break(_) => {
                self.line("break;");
                Ok(())
            }
            Stmt::Continue(_) => {
                self.line("continue;");
                Ok(())
            }
            Stmt::Empty(_) => Ok(()),
            _ => Ok(()),
        }
    }

    fn transpile_decl(&mut self, decl: &Decl) -> Result<()> {
        match decl {
            Decl::Var(var_decl) => self.transpile_var_decl(var_decl),
            Decl::Fn(fn_decl) => self.transpile_fn_decl(fn_decl),
            Decl::TsInterface(iface) => self.transpile_interface(iface),
            Decl::TsTypeAlias(alias) => self.transpile_type_alias(alias),
            _ => Ok(()),
        }
    }

    fn transpile_var_decl(&mut self, var_decl: &VarDecl) -> Result<()> {
        for decl in &var_decl.decls {
            self.push_indent();

            let name = pat_to_string(&decl.name);
            let is_mutated = self.mutated_vars.contains(&name);
            let needs_mut = is_mutated;

            if needs_mut {
                self.push("let mut ");
            } else {
                self.push("let ");
            }
            self.push(&name);

            // Type annotation
            let rust_type = self.resolve_var_type(&decl.name, decl.init.as_deref());
            if rust_type != RustType::Inferred {
                self.push(": ");
                self.push(&rust_type.to_rust_str());
                if rust_type.needs_hashmap_import() {
                    self.needs_hashmap = true;
                }
            }

            if let Some(init) = &decl.init {
                self.push(" = ");
                self.transpile_expr(init)?;
            }
            self.push(";\n");

            self.vars.insert(
                name,
                VarInfo {
                    rust_type,
                    mutable: needs_mut,
                },
            );
        }
        Ok(())
    }

    fn resolve_var_type(&self, pat: &Pat, init: Option<&Expr>) -> RustType {
        // Check for explicit type annotation
        if let Pat::Ident(bind) = pat {
            if let Some(type_ann) = &bind.type_ann {
                return ts_types::resolve_ts_type(&type_ann.type_ann);
            }
        }
        // Infer from initializer
        if let Some(expr) = init {
            return ts_types::infer_from_expr(expr);
        }
        RustType::Inferred
    }

    fn transpile_fn_decl(&mut self, fn_decl: &FnDecl) -> Result<()> {
        let name = fn_decl.ident.sym.to_string();
        self.push_indent();
        self.push("fn ");
        self.push(&name);
        self.push("(");

        if fn_decl.function.as_ref().params.first().is_some() {
            let params = &fn_decl.function.params;
            for (i, param) in params.iter().enumerate() {
                if i > 0 {
                    self.push(", ");
                }
                self.transpile_fn_param(&param.pat)?;
            }
        }

        self.push(")");

        // Return type
        if let Some(ret) = &fn_decl.function.return_type {
            let rt = ts_types::resolve_ts_type(&ret.type_ann);
            if rt != RustType::Void {
                self.push(" -> ");
                self.push(&rt.to_rust_str());
            }
        }

        self.push(" {\n");
        self.indent += 1;

        if let Some(body) = &fn_decl.function.body {
            // Collect mutations in function body
            for s in &body.stmts {
                self.collect_mutations(s);
            }
            for stmt in &body.stmts {
                self.transpile_stmt(stmt)?;
            }
        }

        self.indent -= 1;
        self.line("}");
        self.push("\n");
        Ok(())
    }

    fn transpile_fn_param(&mut self, pat: &Pat) -> Result<()> {
        match pat {
            Pat::Ident(ident) => {
                let name = ident.sym.to_string();
                self.push(&name);
                if let Some(type_ann) = &ident.type_ann {
                    let rt = ts_types::resolve_ts_type(&type_ann.type_ann);
                    self.push(": ");
                    // String params → &str for ergonomics (can be changed)
                    if rt == RustType::String {
                        self.push("&str");
                    } else {
                        self.push(&rt.to_rust_str());
                    }
                } else {
                    self.push(": _");
                }
            }
            _ => self.push("_: _"),
        }
        Ok(())
    }

    fn transpile_if(&mut self, if_stmt: &IfStmt) -> Result<()> {
        self.push_indent();
        self.transpile_if_inner(if_stmt)
    }

    fn transpile_if_inner(&mut self, if_stmt: &IfStmt) -> Result<()> {
        self.push("if ");
        self.transpile_expr(&if_stmt.test)?;
        self.push(" {\n");
        self.indent += 1;
        self.transpile_stmt_body(&if_stmt.cons)?;
        self.indent -= 1;

        if let Some(alt) = &if_stmt.alt {
            if let Stmt::If(else_if) = &**alt {
                self.push_indent();
                self.push("} else ");
                self.transpile_if_inner(else_if)?;
                return Ok(());
            }
            self.push_indent();
            self.push("} else {\n");
            self.indent += 1;
            self.transpile_stmt_body(alt)?;
            self.indent -= 1;
        }
        self.line("}");
        Ok(())
    }

    fn transpile_stmt_body(&mut self, stmt: &Stmt) -> Result<()> {
        match stmt {
            Stmt::Block(block) => {
                for s in &block.stmts {
                    self.transpile_stmt(s)?;
                }
            }
            other => self.transpile_stmt(other)?,
        }
        Ok(())
    }

    fn transpile_for(&mut self, for_stmt: &ForStmt) -> Result<()> {
        // Try to detect: for (let i = 0; i < N; i++) → for i in 0..N
        if let Some(range) = detect_range_for(for_stmt) {
            self.push_indent();
            self.push(&format!("for {} in ", range.var));
            self.transpile_expr(&range.start)?;
            self.push("..");
            self.transpile_expr(&range.end)?;
            self.push(" {\n");
            self.indent += 1;
            self.transpile_stmt_body(&for_stmt.body)?;
            self.indent -= 1;
            self.line("}");
            return Ok(());
        }

        // General for → init; while condition { body; update }
        if let Some(init) = &for_stmt.init {
            match init {
                VarDeclOrExpr::VarDecl(vd) => self.transpile_var_decl(vd)?,
                VarDeclOrExpr::Expr(e) => {
                    self.push_indent();
                    self.transpile_expr(e)?;
                    self.push(";\n");
                }
            }
        }

        self.push_indent();
        self.push("while ");
        if let Some(test) = &for_stmt.test {
            self.transpile_expr(test)?;
        } else {
            self.push("true");
        }
        self.push(" {\n");
        self.indent += 1;
        self.transpile_stmt_body(&for_stmt.body)?;
        if let Some(update) = &for_stmt.update {
            self.push_indent();
            self.transpile_expr(update)?;
            self.push(";\n");
        }
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    fn transpile_for_in(&mut self, fi: &ForInStmt) -> Result<()> {
        self.push_indent();
        self.push("for ");
        self.transpile_for_head(&fi.left)?;
        self.push(" in ");
        self.transpile_expr(&fi.right)?;
        self.push(".keys() {\n");
        self.indent += 1;
        self.transpile_stmt_body(&fi.body)?;
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    fn transpile_for_of(&mut self, fo: &ForOfStmt) -> Result<()> {
        self.push_indent();
        self.push("for ");
        self.transpile_for_head(&fo.left)?;
        self.push(" in &");
        self.transpile_expr(&fo.right)?;
        self.push(" {\n");
        self.indent += 1;
        self.transpile_stmt_body(&fo.body)?;
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    fn transpile_for_head(&mut self, head: &ForHead) -> Result<()> {
        match head {
            ForHead::VarDecl(vd) => {
                if let Some(decl) = vd.decls.first() {
                    self.push(&pat_to_string(&decl.name));
                }
            }
            ForHead::Pat(pat) => {
                self.push(&pat_to_string(pat));
            }
            ForHead::UsingDecl(_) => self.push("_"),
        }
        Ok(())
    }

    fn transpile_while(&mut self, w: &WhileStmt) -> Result<()> {
        self.push_indent();
        self.push("while ");
        self.transpile_expr(&w.test)?;
        self.push(" {\n");
        self.indent += 1;
        self.transpile_stmt_body(&w.body)?;
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    fn transpile_interface(&mut self, iface: &TsInterfaceDecl) -> Result<()> {
        let name = iface.id.sym.to_string();
        let mut def = format!("#[derive(Debug, Clone)]\nstruct {} {{\n", name);

        for member in &iface.body.body {
            if let TsTypeElement::TsPropertySignature(prop) = member {
                if let Expr::Ident(key) = &*prop.key {
                    let field_name = to_snake_case(&key.sym);
                    let field_type = prop
                        .type_ann
                        .as_ref()
                        .map(|ta| ts_types::resolve_ts_type(&ta.type_ann))
                        .unwrap_or(RustType::Dynamic);
                    let actual_type = if prop.optional {
                        RustType::Option(Box::new(field_type))
                    } else {
                        field_type
                    };
                    if actual_type.needs_hashmap_import() {
                        self.needs_hashmap = true;
                    }
                    def.push_str(&format!("    pub {}: {},\n", field_name, actual_type.to_rust_str()));
                }
            }
        }

        def.push_str("}\n");
        self.struct_defs.push(def);
        Ok(())
    }

    fn transpile_type_alias(&mut self, alias: &TsTypeAliasDecl) -> Result<()> {
        let name = alias.id.sym.to_string();
        let rt = ts_types::resolve_ts_type(&alias.type_ann);
        if rt.needs_hashmap_import() {
            self.needs_hashmap = true;
        }
        self.line(&format!("type {} = {};", name, rt.to_rust_str()));
        self.push("\n");
        Ok(())
    }

    // -----------------------------------------------------------------------
    // Expression transpilation
    // -----------------------------------------------------------------------

    fn transpile_expr(&mut self, expr: &Expr) -> Result<()> {
        match expr {
            Expr::Lit(lit) => self.transpile_lit(lit),
            Expr::Ident(ident) => {
                self.push(&ident.sym);
                Ok(())
            }
            Expr::Bin(bin) => self.transpile_bin(bin),
            Expr::Unary(unary) => self.transpile_unary(unary),
            Expr::Update(update) => self.transpile_update(update),
            Expr::Assign(assign) => self.transpile_assign(assign),
            Expr::Call(call) => self.transpile_call(call),
            Expr::Member(member) => self.transpile_member(member),
            Expr::Array(arr) => self.transpile_array(arr),
            Expr::Object(obj) => self.transpile_object(obj),
            Expr::Paren(paren) => {
                self.push("(");
                self.transpile_expr(&paren.expr)?;
                self.push(")");
                Ok(())
            }
            Expr::Arrow(arrow) => self.transpile_arrow(arrow),
            Expr::Cond(cond) => self.transpile_cond(cond),
            Expr::Tpl(tpl) => self.transpile_template_lit(tpl),
            Expr::New(new_expr) => self.transpile_new(new_expr),
            Expr::Seq(seq) => {
                self.push("{ ");
                for (i, e) in seq.exprs.iter().enumerate() {
                    if i > 0 {
                        self.push("; ");
                    }
                    self.transpile_expr(e)?;
                }
                self.push(" }");
                Ok(())
            }
            Expr::TsAs(as_expr) => {
                // Type assertion — just emit the expression
                self.transpile_expr(&as_expr.expr)
            }
            Expr::TsNonNull(nn) => self.transpile_expr(&nn.expr),
            _ => {
                self.push("/* unsupported expr */");
                Ok(())
            }
        }
    }

    fn transpile_lit(&mut self, lit: &Lit) -> Result<()> {
        match lit {
            Lit::Num(n) => {
                if n.value.fract() == 0.0 && n.value.abs() < i64::MAX as f64 {
                    self.push(&format!("{}", n.value as i64));
                } else {
                    self.push(&format!("{}_f64", n.value));
                }
            }
            Lit::Str(s) => {
                self.push(&format!("{:?}.to_string()", &*s.value));
            }
            Lit::Bool(b) => {
                self.push(if b.value { "true" } else { "false" });
            }
            Lit::Null(_) => {
                self.push("None");
            }
            _ => self.push("/* unsupported literal */"),
        }
        Ok(())
    }

    fn transpile_bin(&mut self, bin: &BinExpr) -> Result<()> {
        // String concatenation: "a" + b → format!("{}{}", a, b)
        if bin.op == BinaryOp::Add && self.is_string_context(bin) {
            return self.transpile_string_concat(bin);
        }

        self.transpile_expr(&bin.left)?;
        self.push(" ");
        self.push(bin_op_to_rust(bin.op));
        self.push(" ");
        self.transpile_expr(&bin.right)?;
        Ok(())
    }

    fn is_string_context(&self, bin: &BinExpr) -> bool {
        ts_types::infer_from_expr(&Expr::Bin(bin.clone())) == RustType::String
            || ts_types::infer_from_expr(&bin.left) == RustType::String
            || ts_types::infer_from_expr(&bin.right) == RustType::String
    }

    fn transpile_string_concat(&mut self, bin: &BinExpr) -> Result<()> {
        let mut parts = Vec::new();
        self.collect_concat_parts(&Expr::Bin(bin.clone()), &mut parts);

        self.push("format!(\"");
        for _ in &parts {
            self.push("{}");
        }
        self.push("\"");
        for part in &parts {
            self.push(", ");
            // For string literals, emit directly without .to_string()
            match &**part {
                Expr::Lit(Lit::Str(s)) => {
                    self.push(&format!("{:?}", &*s.value));
                }
                _ => {
                    self.transpile_expr(part)?;
                }
            }
        }
        self.push(")");
        Ok(())
    }

    fn collect_concat_parts<'a>(&self, expr: &'a Expr, parts: &mut Vec<Box<Expr>>) {
        if let Expr::Bin(bin) = expr {
            if bin.op == BinaryOp::Add
                && (ts_types::infer_from_expr(&bin.left) == RustType::String
                    || ts_types::infer_from_expr(&bin.right) == RustType::String)
            {
                self.collect_concat_parts(&bin.left, parts);
                self.collect_concat_parts(&bin.right, parts);
                return;
            }
        }
        parts.push(Box::new(expr.clone()));
    }

    fn transpile_unary(&mut self, unary: &UnaryExpr) -> Result<()> {
        match unary.op {
            UnaryOp::Bang => {
                self.push("!");
                self.transpile_expr(&unary.arg)?;
            }
            UnaryOp::Minus => {
                self.push("-");
                self.transpile_expr(&unary.arg)?;
            }
            UnaryOp::Plus => {
                self.transpile_expr(&unary.arg)?;
            }
            UnaryOp::TypeOf => {
                self.push("type_of(");
                self.transpile_expr(&unary.arg)?;
                self.push(")");
            }
            _ => {
                self.push("/* unsupported unary */");
            }
        }
        Ok(())
    }

    fn transpile_update(&mut self, update: &UpdateExpr) -> Result<()> {
        let ident = if let Expr::Ident(i) = &*update.arg {
            i.sym.to_string()
        } else {
            "???".into()
        };

        match update.op {
            UpdateOp::PlusPlus => {
                self.push(&ident);
                self.push(" += 1");
            }
            UpdateOp::MinusMinus => {
                self.push(&ident);
                self.push(" -= 1");
            }
        }
        Ok(())
    }

    fn transpile_assign(&mut self, assign: &AssignExpr) -> Result<()> {
        self.transpile_assign_target(&assign.left)?;
        self.push(" ");
        self.push(assign_op_to_rust(assign.op));
        self.push(" ");
        self.transpile_expr(&assign.right)?;
        Ok(())
    }

    fn transpile_assign_target(&mut self, target: &AssignTarget) -> Result<()> {
        match target {
            AssignTarget::Simple(simple) => match simple {
                SimpleAssignTarget::Ident(ident) => {
                    self.push(&ident.sym);
                }
                SimpleAssignTarget::Member(member) => {
                    self.transpile_member(member)?;
                }
                _ => self.push("/* unsupported assign target */"),
            },
            AssignTarget::Pat(_) => self.push("/* destructuring assign */"),
        }
        Ok(())
    }

    fn transpile_call(&mut self, call: &CallExpr) -> Result<()> {
        match &call.callee {
            Callee::Expr(callee) => {
                // Special case: console.log(...)
                if is_console_log(callee) {
                    return self.transpile_console_log(&call.args);
                }

                // Method calls: obj.method(...)
                if let Expr::Member(member) = &**callee {
                    return self.transpile_method_call(member, &call.args);
                }

                self.transpile_expr(callee)?;
                self.push("(");
                self.transpile_args(&call.args)?;
                self.push(")");
            }
            _ => self.push("/* unsupported callee */"),
        }
        Ok(())
    }

    fn transpile_console_log(&mut self, args: &[ExprOrSpread]) -> Result<()> {
        if args.is_empty() {
            self.push("println!()");
            return Ok(());
        }

        // Optimize: if single string literal, embed directly in format string
        if args.len() == 1 {
            if let Expr::Lit(Lit::Str(s)) = &*args[0].expr {
                self.push(&format!("println!({:?})", &*s.value));
                return Ok(());
            }
        }

        let fmt_parts: Vec<String> = args.iter().map(|_| "{}".to_string()).collect();
        self.push(&format!("println!(\"{}\"", fmt_parts.join(" ")));
        for arg in args {
            self.push(", ");
            // For string literals in println!, no need for .to_string()
            match &*arg.expr {
                Expr::Lit(Lit::Str(s)) => {
                    self.push(&format!("{:?}", &*s.value));
                }
                _ => self.transpile_expr(&arg.expr)?,
            }
        }
        self.push(")");
        Ok(())
    }

    fn transpile_method_call(
        &mut self,
        member: &MemberExpr,
        args: &[ExprOrSpread],
    ) -> Result<()> {
        let method_name = match &member.prop {
            MemberProp::Ident(ident) => ident.sym.to_string(),
            _ => {
                self.transpile_expr(&member.obj)?;
                self.push("./* unknown method */()");
                return Ok(());
            }
        };

        match method_name.as_str() {
            "push" => {
                self.transpile_expr(&member.obj)?;
                self.push(".push(");
                self.transpile_args(args)?;
                self.push(")");
            }
            "pop" => {
                self.transpile_expr(&member.obj)?;
                self.push(".pop()");
            }
            "length" | "len" => {
                self.transpile_expr(&member.obj)?;
                self.push(".len()");
            }
            "toString" | "to_string" => {
                self.transpile_expr(&member.obj)?;
                self.push(".to_string()");
            }
            "indexOf" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter().position(|x| x == &");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(").map(|i| i as f64).unwrap_or(-1_f64)");
            }
            "includes" => {
                self.transpile_expr(&member.obj)?;
                self.push(".contains(&");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "map" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter().map(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(").collect::<Vec<_>>()");
            }
            "filter" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter().filter(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(").cloned().collect::<Vec<_>>()");
            }
            "forEach" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter().for_each(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "reduce" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter().fold(");
                if let Some(init) = args.get(1) {
                    self.transpile_expr(&init.expr)?;
                } else {
                    self.push("Default::default()");
                }
                self.push(", ");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "join" => {
                self.transpile_expr(&member.obj)?;
                self.push(".join(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                } else {
                    self.push("\",\"");
                }
                self.push(")");
            }
            "slice" => {
                self.transpile_expr(&member.obj)?;
                self.push("[");
                if let Some(start) = args.first() {
                    self.transpile_expr(&start.expr)?;
                } else {
                    self.push("0");
                }
                self.push(" as usize..");
                if let Some(end) = args.get(1) {
                    self.transpile_expr(&end.expr)?;
                    self.push(" as usize");
                }
                self.push("].to_vec()");
            }
            "keys" => {
                self.transpile_expr(&member.obj)?;
                self.push(".keys()");
            }
            "values" => {
                self.transpile_expr(&member.obj)?;
                self.push(".values()");
            }
            "entries" => {
                self.transpile_expr(&member.obj)?;
                self.push(".iter()");
            }
            "has" => {
                self.transpile_expr(&member.obj)?;
                self.push(".contains_key(&");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "set" => {
                self.transpile_expr(&member.obj)?;
                self.push(".insert(");
                self.transpile_args(args)?;
                self.push(")");
            }
            "get" => {
                self.transpile_expr(&member.obj)?;
                self.push(".get(&");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "delete" => {
                self.transpile_expr(&member.obj)?;
                self.push(".remove(&");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "trim" => {
                self.transpile_expr(&member.obj)?;
                self.push(".trim().to_string()");
            }
            "split" => {
                self.transpile_expr(&member.obj)?;
                self.push(".split(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(").map(|s| s.to_string()).collect::<Vec<_>>()");
            }
            "replace" => {
                self.transpile_expr(&member.obj)?;
                self.push(".replacen(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(", ");
                if let Some(arg) = args.get(1) {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(", 1).to_string()");
            }
            "startsWith" => {
                self.transpile_expr(&member.obj)?;
                self.push(".starts_with(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "endsWith" => {
                self.transpile_expr(&member.obj)?;
                self.push(".ends_with(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(")");
            }
            "toUpperCase" => {
                self.transpile_expr(&member.obj)?;
                self.push(".to_uppercase()");
            }
            "toLowerCase" => {
                self.transpile_expr(&member.obj)?;
                self.push(".to_lowercase()");
            }
            "charAt" => {
                self.transpile_expr(&member.obj)?;
                self.push(".chars().nth(");
                if let Some(arg) = args.first() {
                    self.transpile_expr(&arg.expr)?;
                }
                self.push(" as usize).map(|c| c.to_string()).unwrap_or_default()");
            }
            "abs" | "floor" | "ceil" | "round" | "sqrt" => {
                // Math.abs(x) → x.abs(), etc.
                self.transpile_expr(&member.obj)?;
                self.push(&format!(".{}()", method_name));
            }
            _ => {
                // Generic method call
                self.transpile_expr(&member.obj)?;
                self.push(".");
                self.push(&method_name);
                self.push("(");
                self.transpile_args(args)?;
                self.push(")");
            }
        }
        Ok(())
    }

    fn transpile_member(&mut self, member: &MemberExpr) -> Result<()> {
        // Special: .length → .len()
        if let MemberProp::Ident(prop) = &member.prop {
            if prop.sym.as_ref() == "length" {
                self.transpile_expr(&member.obj)?;
                self.push(".len()");
                return Ok(());
            }
            // Math.PI, Math.E, etc.
            if let Expr::Ident(obj) = &*member.obj {
                if obj.sym.as_ref() == "Math" {
                    return self.transpile_math_prop(&prop.sym);
                }
            }
        }

        self.transpile_expr(&member.obj)?;

        match &member.prop {
            MemberProp::Ident(ident) => {
                self.push(".");
                self.push(&ident.sym);
            }
            MemberProp::Computed(computed) => {
                // obj[key] → obj[key] (for arrays) or obj.get(&key) (for maps)
                // Heuristic: if key is a number, use array index; otherwise map access
                let key_type = ts_types::infer_from_expr(&computed.expr);
                if key_type == RustType::F64 {
                    self.push("[");
                    self.transpile_expr(&computed.expr)?;
                    self.push(" as usize]");
                } else {
                    self.push("[&");
                    self.transpile_expr(&computed.expr)?;
                    self.push("]");
                }
            }
            _ => {}
        }
        Ok(())
    }

    fn transpile_math_prop(&mut self, prop: &str) -> Result<()> {
        match prop {
            "PI" => self.push("std::f64::consts::PI"),
            "E" => self.push("std::f64::consts::E"),
            "abs" | "floor" | "ceil" | "round" | "sqrt" | "sin" | "cos" | "tan" | "log"
            | "log2" | "log10" | "pow" | "min" | "max" | "random" => {
                self.push(&format!("f64::{}", prop));
            }
            _ => self.push(&format!("/* Math.{} */", prop)),
        }
        Ok(())
    }

    fn transpile_array(&mut self, arr: &ArrayLit) -> Result<()> {
        self.push("vec![");
        for (i, elem) in arr.elems.iter().enumerate() {
            if i > 0 {
                self.push(", ");
            }
            if let Some(e) = elem {
                self.transpile_expr(&e.expr)?;
            }
        }
        self.push("]");
        Ok(())
    }

    fn transpile_object(&mut self, obj: &ObjectLit) -> Result<()> {
        if obj.props.is_empty() {
            self.push("HashMap::new()");
            self.needs_hashmap = true;
            return Ok(());
        }

        // Check if all keys are identifiers/strings → HashMap literal
        self.needs_hashmap = true;
        self.push("{\n");
        self.indent += 1;
        self.push_indent();
        self.push("let mut _obj = HashMap::new();\n");
        for prop in &obj.props {
            if let PropOrSpread::Prop(prop) = prop {
                if let Prop::KeyValue(kv) = &**prop {
                    self.push_indent();
                    self.push("_obj.insert(");
                    self.transpile_prop_name(&kv.key)?;
                    self.push(", ");
                    self.transpile_expr(&kv.value)?;
                    self.push(");\n");
                }
            }
        }
        self.push_indent();
        self.push("_obj\n");
        self.indent -= 1;
        self.push_indent();
        self.push("}");
        Ok(())
    }

    fn transpile_prop_name(&mut self, name: &PropName) -> Result<()> {
        match name {
            PropName::Ident(ident) => {
                self.push(&format!("{:?}.to_string()", &*ident.sym));
            }
            PropName::Str(s) => {
                self.push(&format!("{:?}.to_string()", &*s.value));
            }
            PropName::Num(n) => {
                self.push(&format!("{}_f64", n.value));
            }
            PropName::Computed(c) => {
                self.transpile_expr(&c.expr)?;
            }
            _ => self.push("\"\""),
        }
        Ok(())
    }

    fn transpile_arrow(&mut self, arrow: &ArrowExpr) -> Result<()> {
        self.push("|");
        for (i, param) in arrow.params.iter().enumerate() {
            if i > 0 {
                self.push(", ");
            }
            self.push(&pat_to_string(param));
        }
        self.push("| ");

        match &*arrow.body {
            BlockStmtOrExpr::Expr(expr) => {
                self.transpile_expr(expr)?;
            }
            BlockStmtOrExpr::BlockStmt(block) => {
                self.push("{\n");
                self.indent += 1;
                for stmt in &block.stmts {
                    self.transpile_stmt(stmt)?;
                }
                self.indent -= 1;
                self.push_indent();
                self.push("}");
            }
        }
        Ok(())
    }

    fn transpile_cond(&mut self, cond: &CondExpr) -> Result<()> {
        self.push("if ");
        self.transpile_expr(&cond.test)?;
        self.push(" { ");
        self.transpile_expr(&cond.cons)?;
        self.push(" } else { ");
        self.transpile_expr(&cond.alt)?;
        self.push(" }");
        Ok(())
    }

    fn transpile_template_lit(&mut self, tpl: &Tpl) -> Result<()> {
        self.push("format!(\"");
        for (i, quasi) in tpl.quasis.iter().enumerate() {
            // Escape the raw text for format string
            let raw = quasi.raw.replace('{', "{{").replace('}', "}}");
            self.push(&raw);
            if i < tpl.exprs.len() {
                self.push("{}");
            }
        }
        self.push("\"");
        for expr in &tpl.exprs {
            self.push(", ");
            self.transpile_expr(expr)?;
        }
        self.push(")");
        Ok(())
    }

    fn transpile_new(&mut self, new_expr: &NewExpr) -> Result<()> {
        if let Expr::Ident(ident) = &*new_expr.callee {
            match ident.sym.as_ref() {
                "Map" => {
                    self.push("HashMap::new()");
                    self.needs_hashmap = true;
                }
                "Set" => {
                    self.push("HashSet::new()");
                }
                "Array" => {
                    self.push("Vec::new()");
                }
                name => {
                    self.push(name);
                    self.push("::new(");
                    if let Some(args) = &new_expr.args {
                        self.transpile_args(args)?;
                    }
                    self.push(")");
                }
            }
        }
        Ok(())
    }

    fn transpile_args(&mut self, args: &[ExprOrSpread]) -> Result<()> {
        for (i, arg) in args.iter().enumerate() {
            if i > 0 {
                self.push(", ");
            }
            self.transpile_expr(&arg.expr)?;
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn pat_to_string(pat: &Pat) -> String {
    match pat {
        Pat::Ident(ident) => ident.sym.to_string(),
        Pat::Array(arr) => {
            let elems: Vec<_> = arr
                .elems
                .iter()
                .map(|e| e.as_ref().map(pat_to_string).unwrap_or("_".into()))
                .collect();
            format!("[{}]", elems.join(", "))
        }
        Pat::Rest(rest) => format!("..{}", pat_to_string(&rest.arg)),
        Pat::Assign(a) => pat_to_string(&a.left),
        _ => "_".into(),
    }
}

fn pat_target_name(target: &AssignTarget) -> Option<String> {
    match target {
        AssignTarget::Simple(SimpleAssignTarget::Ident(ident)) => {
            Some(ident.sym.to_string())
        }
        _ => None,
    }
}

fn is_fn_decl(stmt: &Stmt) -> bool {
    matches!(stmt, Stmt::Decl(Decl::Fn(_)))
}

fn is_main_fn(stmt: &Stmt) -> bool {
    if let Stmt::Decl(Decl::Fn(fn_decl)) = stmt {
        fn_decl.ident.sym.as_ref() == "main"
    } else {
        false
    }
}

fn is_console_log(expr: &Expr) -> bool {
    if let Expr::Member(member) = expr {
        if let Expr::Ident(obj) = &*member.obj {
            if let MemberProp::Ident(prop) = &member.prop {
                return obj.sym.as_ref() == "console"
                    && matches!(prop.sym.as_ref(), "log" | "warn" | "error" | "info");
            }
        }
    }
    false
}

struct RangeFor<'a> {
    var: String,
    start: &'a Expr,
    end: &'a Expr,
}

/// Detect `for (let i = START; i < END; i++)` → range pattern
fn detect_range_for(for_stmt: &ForStmt) -> Option<RangeFor<'_>> {
    // init: let i = START
    let (var_name, start) = match &for_stmt.init {
        Some(VarDeclOrExpr::VarDecl(vd)) => {
            let decl = vd.decls.first()?;
            let name = pat_to_string(&decl.name);
            let init = decl.init.as_deref()?;
            (name, init)
        }
        _ => return None,
    };

    // test: i < END
    let end = match &for_stmt.test {
        Some(test) => {
            if let Expr::Bin(bin) = &**test {
                if bin.op == BinaryOp::Lt {
                    if let Expr::Ident(ident) = &*bin.left {
                        if ident.sym.as_ref() == var_name {
                            &*bin.right
                        } else {
                            return None;
                        }
                    } else {
                        return None;
                    }
                } else {
                    return None;
                }
            } else {
                return None;
            }
        }
        None => return None,
    };

    // update: i++ or i += 1
    match &for_stmt.update {
        Some(update) => match &**update {
            Expr::Update(u) => {
                if u.op == UpdateOp::PlusPlus {
                    if let Expr::Ident(ident) = &*u.arg {
                        if ident.sym.as_ref() != var_name {
                            return None;
                        }
                    }
                } else {
                    return None;
                }
            }
            Expr::Assign(a) => {
                if a.op != AssignOp::AddAssign {
                    return None;
                }
            }
            _ => return None,
        },
        None => return None,
    }

    Some(RangeFor {
        var: var_name,
        start,
        end,
    })
}

fn bin_op_to_rust(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Mod => "%",
        BinaryOp::EqEq | BinaryOp::EqEqEq => "==",
        BinaryOp::NotEq | BinaryOp::NotEqEq => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::LtEq => "<=",
        BinaryOp::Gt => ">",
        BinaryOp::GtEq => ">=",
        BinaryOp::LogicalAnd => "&&",
        BinaryOp::LogicalOr => "||",
        BinaryOp::BitAnd => "&",
        BinaryOp::BitOr => "|",
        BinaryOp::BitXor => "^",
        BinaryOp::LShift => "<<",
        BinaryOp::RShift => ">>",
        BinaryOp::Exp => "/* ** */",
        _ => "/* unknown op */",
    }
}

fn assign_op_to_rust(op: AssignOp) -> &'static str {
    match op {
        AssignOp::Assign => "=",
        AssignOp::AddAssign => "+=",
        AssignOp::SubAssign => "-=",
        AssignOp::MulAssign => "*=",
        AssignOp::DivAssign => "/=",
        AssignOp::ModAssign => "%=",
        AssignOp::BitAndAssign => "&=",
        AssignOp::BitOrAssign => "|=",
        AssignOp::BitXorAssign => "^=",
        AssignOp::LShiftAssign => "<<=",
        AssignOp::RShiftAssign => ">>=",
        _ => "= /* unsupported op */",
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn transpile_ok(source: &str) -> String {
        transpile(source).expect("transpile failed")
    }

    #[test]
    fn basic_variable() {
        let rust = transpile_ok("let x: number = 42;");
        assert!(rust.contains("let x: f64 = 42;"), "got: {rust}");
    }

    #[test]
    fn string_variable() {
        let rust = transpile_ok(r#"let name: string = "hello";"#);
        assert!(rust.contains(r#"let name: String = "hello".to_string();"#), "got: {rust}");
    }

    #[test]
    fn function_declaration() {
        let rust = transpile_ok("function add(a: number, b: number): number { return a + b; }");
        assert!(rust.contains("fn add(a: f64, b: f64) -> f64"), "got: {rust}");
    }

    #[test]
    fn console_log() {
        let rust = transpile_ok(r#"console.log("hello");"#);
        assert!(rust.contains("println!"), "got: {rust}");
    }

    #[test]
    fn array_push() {
        let rust = transpile_ok(r#"let items: number[] = [1, 2, 3]; items.push(4);"#);
        assert!(rust.contains("vec!["), "got: {rust}");
        assert!(rust.contains(".push("), "got: {rust}");
    }

    #[test]
    fn for_loop_range() {
        let rust = transpile_ok("for (let i = 0; i < 10; i++) { console.log(i); }");
        assert!(rust.contains("for i in 0..10"), "got: {rust}");
    }

    #[test]
    fn if_else() {
        let rust = transpile_ok("let x = 5; if (x > 3) { console.log(x); } else { console.log(0); }");
        assert!(rust.contains("if x > 3"), "got: {rust}");
        assert!(rust.contains("} else {"), "got: {rust}");
    }

    #[test]
    fn interface_to_struct() {
        let rust = transpile_ok("interface User { name: string; age: number; email?: string; }");
        assert!(rust.contains("struct User"), "got: {rust}");
        assert!(rust.contains("pub name: String"), "got: {rust}");
        assert!(rust.contains("pub age: f64"), "got: {rust}");
        assert!(rust.contains("pub email: Option<String>"), "got: {rust}");
    }

    #[test]
    fn while_loop() {
        let rust = transpile_ok("let x = 0; while (x < 10) { x += 1; }");
        assert!(rust.contains("while x < 10"), "got: {rust}");
    }

    #[test]
    fn for_of_loop() {
        let rust = transpile_ok("let items = [1, 2, 3]; for (let item of items) { console.log(item); }");
        assert!(rust.contains("for item in &items"), "got: {rust}");
    }

    #[test]
    fn arrow_function() {
        let rust = transpile_ok("let nums = [1, 2, 3]; let doubled = nums.map((x) => x * 2);");
        assert!(rust.contains("|x| x * 2"), "got: {rust}");
    }

    #[test]
    fn template_literal() {
        let rust = transpile_ok(r#"let name = "world"; let msg = `hello ${name}`;"#);
        assert!(rust.contains("format!("), "got: {rust}");
    }

    #[test]
    fn string_concat() {
        let rust = transpile_ok(r#"let greeting = "Hello, " + "world!";"#);
        assert!(rust.contains("format!("), "got: {rust}");
    }

    #[test]
    fn nullable_type() {
        let rust = transpile_ok("let x: number | null = null;");
        assert!(rust.contains("Option<f64>"), "got: {rust}");
        assert!(rust.contains("None"), "got: {rust}");
    }

    #[test]
    fn hashmap_record_type() {
        let rust = transpile_ok("let obj: Record<string, number> = {};");
        assert!(rust.contains("HashMap<String, f64>"), "got: {rust}");
        assert!(rust.contains("HashMap::new()"), "got: {rust}");
    }

    #[test]
    fn mutable_variable() {
        let rust = transpile_ok("let count = 0; count = count + 1;");
        assert!(rust.contains("let mut count"), "got: {rust}");
    }

    #[test]
    fn method_length() {
        let rust = transpile_ok("let items = [1, 2, 3]; let n = items.length;");
        assert!(rust.contains(".len()"), "got: {rust}");
    }
}
