//! Generate browser-facing Rust facade skeletons from TypeScript declarations.
//!
//! The output is intentionally not wired into `w3cos-runtime`: every generated
//! constructor, method, getter, and setter contains a named `todo!()` so the
//! implementation boundary remains explicit during review.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::Path;

use anyhow::{Result, anyhow, bail};
use swc_common::{FileName, SourceMap, sync::Lrc};
use swc_ecma_ast::{
    Decl, Expr, Lit, Module, ModuleItem, Pat, Stmt, TsInterfaceDecl, TsType, TsTypeElement,
};
use swc_ecma_parser::{Parser, StringInput, Syntax, TsSyntax};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MemberKind {
    Method,
    Property { readonly: bool },
}

#[derive(Debug, Clone, Default)]
struct Interface {
    extends: BTreeSet<String>,
    members: BTreeMap<String, MemberKind>,
}

#[derive(Debug, Default)]
struct DeclarationIndex {
    interfaces: BTreeMap<String, Interface>,
    constructors: HashSet<String>,
}

/// Generate Rust `Value` facades for the selected TypeScript interfaces.
///
/// When `own_only` is false, members from inherited interfaces are included.
/// Interfaces backed by a `declare var X: { new(...): X }` declaration also
/// receive an `x_class()` constructor skeleton.
pub fn generate(
    source: &str,
    source_name: &Path,
    interface_names: &[String],
    own_only: bool,
) -> Result<String> {
    if interface_names.is_empty() {
        bail!("at least one --interface is required");
    }

    let module = parse_declarations(source, source_name)?;
    let index = index_declarations(&module);
    let mut output = String::new();
    output.push_str("//! Auto-generated by `w3cos web-api-skeleton` — review before wiring.\n");
    output.push_str(&format!("//! Source: {}\n", source_name.display()));
    output.push_str("//! Every generated operation intentionally fails with a named TODO.\n\n");
    output.push_str("#![allow(dead_code, unreachable_code, unused_variables)]\n\n");
    output.push_str("use std::collections::HashMap;\n");
    output.push_str("use w3cos_core::Value;\n\n");

    for interface_name in interface_names {
        let Some(interface) = index.interfaces.get(interface_name) else {
            bail!("TypeScript interface {interface_name:?} was not found");
        };
        let members = if own_only {
            interface.members.clone()
        } else {
            collect_members(&index.interfaces, interface_name)?
        };
        emit_interface(
            &mut output,
            interface_name,
            &members,
            index.constructors.contains(interface_name),
        );
    }

    Ok(output)
}

fn parse_declarations(source: &str, source_name: &Path) -> Result<Module> {
    let source_map: Lrc<SourceMap> = Default::default();
    let file = source_map.new_source_file(
        Lrc::new(FileName::Real(source_name.to_path_buf())),
        source.to_string(),
    );
    let mut parser = Parser::new(
        Syntax::Typescript(TsSyntax {
            dts: true,
            ..Default::default()
        }),
        StringInput::from(&*file),
        None,
    );
    parser.parse_module().map_err(|error| {
        anyhow!(
            "TypeScript declaration parse error in {}: {error:?}",
            source_name.display()
        )
    })
}

fn index_declarations(module: &Module) -> DeclarationIndex {
    let mut index = DeclarationIndex::default();
    for item in &module.body {
        let ModuleItem::Stmt(Stmt::Decl(declaration)) = item else {
            continue;
        };
        match declaration {
            Decl::TsInterface(interface) => index_interface(&mut index, interface),
            Decl::Var(variable) => {
                for declaration in &variable.decls {
                    let Pat::Ident(binding) = &declaration.name else {
                        continue;
                    };
                    let Some(type_annotation) = &binding.type_ann else {
                        continue;
                    };
                    let TsType::TsTypeLit(type_literal) = type_annotation.type_ann.as_ref() else {
                        continue;
                    };
                    if type_literal
                        .members
                        .iter()
                        .any(|member| matches!(member, TsTypeElement::TsConstructSignatureDecl(_)))
                    {
                        index.constructors.insert(binding.id.sym.to_string());
                    }
                }
            }
            _ => {}
        }
    }
    index
}

fn index_interface(index: &mut DeclarationIndex, declaration: &TsInterfaceDecl) {
    let interface = index
        .interfaces
        .entry(declaration.id.sym.to_string())
        .or_default();
    for parent in &declaration.extends {
        if let Some(name) = expression_name(&parent.expr) {
            interface.extends.insert(name);
        }
    }
    for member in &declaration.body.body {
        match member {
            TsTypeElement::TsMethodSignature(method) => {
                if let Some(name) = expression_name(&method.key) {
                    interface.members.insert(name, MemberKind::Method);
                }
            }
            TsTypeElement::TsPropertySignature(property) => {
                if let Some(name) = expression_name(&property.key) {
                    interface.members.insert(
                        name,
                        MemberKind::Property {
                            readonly: property.readonly,
                        },
                    );
                }
            }
            TsTypeElement::TsGetterSignature(getter) => {
                if let Some(name) = expression_name(&getter.key) {
                    interface
                        .members
                        .insert(name, MemberKind::Property { readonly: true });
                }
            }
            TsTypeElement::TsSetterSignature(setter) => {
                if let Some(name) = expression_name(&setter.key) {
                    interface
                        .members
                        .insert(name, MemberKind::Property { readonly: false });
                }
            }
            _ => {}
        }
    }
}

fn collect_members(
    interfaces: &BTreeMap<String, Interface>,
    interface_name: &str,
) -> Result<BTreeMap<String, MemberKind>> {
    fn visit(
        interfaces: &BTreeMap<String, Interface>,
        name: &str,
        visiting: &mut HashSet<String>,
        members: &mut BTreeMap<String, MemberKind>,
    ) -> Result<()> {
        if !visiting.insert(name.to_string()) {
            bail!("cyclic TypeScript interface inheritance at {name}");
        }
        let interface = interfaces
            .get(name)
            .ok_or_else(|| anyhow!("inherited TypeScript interface {name:?} was not found"))?;
        for parent in &interface.extends {
            visit(interfaces, parent, visiting, members)?;
        }
        members.extend(interface.members.clone());
        visiting.remove(name);
        Ok(())
    }

    let mut members = BTreeMap::new();
    visit(
        interfaces,
        interface_name,
        &mut HashSet::new(),
        &mut members,
    )?;
    Ok(members)
}

fn expression_name(expression: &Expr) -> Option<String> {
    match expression {
        Expr::Ident(identifier) => Some(identifier.sym.to_string()),
        Expr::Lit(Lit::Str(string)) => Some(wtf8_to_string(&string.value)),
        Expr::Member(member) => {
            let object = expression_name(&member.obj)?;
            let property = match &member.prop {
                swc_ecma_ast::MemberProp::Ident(identifier) => identifier.sym.to_string(),
                _ => return None,
            };
            Some(format!("{object}.{property}"))
        }
        _ => None,
    }
}

fn emit_interface(
    output: &mut String,
    interface_name: &str,
    members: &BTreeMap<String, MemberKind>,
    constructable: bool,
) {
    let rust_name = to_snake_case(interface_name);
    output.push_str(&format!("/// W3C `{interface_name}` facade skeleton.\n"));
    if constructable {
        output.push_str(&format!("pub fn {rust_name}_class() -> Value {{\n"));
        output.push_str("    Value::function(|_this, _arguments| {\n");
        output.push_str(&format!(
            "        todo!(\"Web API TODO: {interface_name}.constructor\")\n"
        ));
        output.push_str("    })\n");
        output.push_str("}\n\n");
    }

    output.push_str(&format!("pub fn {rust_name}_value() -> Value {{\n"));
    output.push_str("    let mut properties: HashMap<String, Value> = HashMap::new();\n");
    for (name, kind) in members {
        match kind {
            MemberKind::Method => {
                output.push_str("    properties.insert(\n");
                output.push_str(&format!("        {name:?}.to_string(),\n"));
                output.push_str("        Value::function(|_this, _arguments| {\n");
                output.push_str(&format!(
                    "            todo!(\"Web API TODO: {interface_name}.{name}\")\n"
                ));
                output.push_str("        }),\n");
                output.push_str("    );\n");
            }
            MemberKind::Property { readonly } => {
                output.push_str("    properties.insert(\n");
                output.push_str(&format!("        \"__w3cos_getter_{name}\".to_string(),\n"));
                output.push_str("        Value::function(|_this, _arguments| {\n");
                output.push_str(&format!(
                    "            todo!(\"Web API TODO: {interface_name}.{name}.get\")\n"
                ));
                output.push_str("        }),\n");
                output.push_str("    );\n");
                if !readonly {
                    output.push_str("    properties.insert(\n");
                    output.push_str(&format!("        \"__w3cos_setter_{name}\".to_string(),\n"));
                    output.push_str("        Value::function(|_this, _arguments| {\n");
                    output.push_str(&format!(
                        "            todo!(\"Web API TODO: {interface_name}.{name}.set\")\n"
                    ));
                    output.push_str("        }),\n");
                    output.push_str("    );\n");
                }
            }
        }
    }
    output.push_str("    Value::object(properties)\n");
    output.push_str("}\n\n");
}

fn to_snake_case(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut output = String::new();
    for (index, character) in chars.iter().copied().enumerate() {
        if character.is_ascii_uppercase() {
            let previous_is_lowercase = index > 0 && chars[index - 1].is_ascii_lowercase();
            let next_is_lowercase = chars
                .get(index + 1)
                .is_some_and(|next| next.is_ascii_lowercase());
            if index > 0 && (previous_is_lowercase || next_is_lowercase) {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
        } else if character.is_ascii_alphanumeric() || character == '_' {
            output.push(character);
        } else {
            output.push('_');
        }
    }
    output
}

fn wtf8_to_string(atom: &impl std::fmt::Debug) -> String {
    let debug = format!("{atom:?}");
    serde_json::from_str(&debug).unwrap_or_else(|_| {
        debug
            .strip_prefix('"')
            .and_then(|value| value.strip_suffix('"'))
            .unwrap_or(&debug)
            .to_string()
    })
}

#[cfg(test)]
mod tests {
    use super::generate;
    use std::path::Path;

    #[test]
    fn generates_inherited_constructor_facade_with_named_todos() {
        let source = r#"
            interface EventTarget {
                addEventListener(type: string, callback: unknown): void;
            }
            interface Event extends EventTarget {
                readonly type: string;
                cancelBubble: boolean;
                composedPath(): EventTarget[];
                composedPath(): EventTarget[];
            }
            declare var Event: {
                prototype: Event;
                new(type: string): Event;
            };
        "#;
        let output = generate(
            source,
            Path::new("fixture.d.ts"),
            &["Event".to_string()],
            false,
        )
        .expect("generate skeleton");

        assert!(output.contains("pub fn event_class() -> Value"));
        assert!(output.contains("Web API TODO: Event.constructor"));
        assert!(output.contains("Web API TODO: Event.addEventListener"));
        assert!(output.contains("Web API TODO: Event.type.get"));
        assert!(!output.contains("Event.type.set"));
        assert!(output.contains("Web API TODO: Event.cancelBubble.set"));
        assert_eq!(
            output.matches("Web API TODO: Event.composedPath").count(),
            1
        );
    }

    #[test]
    fn own_only_excludes_inherited_members() {
        let source = r#"
            interface Parent { inherited(): void; }
            interface Child extends Parent { own(): void; }
        "#;
        let output = generate(
            source,
            Path::new("fixture.d.ts"),
            &["Child".to_string()],
            true,
        )
        .expect("generate skeleton");

        assert!(output.contains("Web API TODO: Child.own"));
        assert!(!output.contains("inherited"));
        assert!(!output.contains("child_class"));
        assert!(output.contains("pub fn child_value() -> Value"));
    }

    #[test]
    fn reports_missing_interface() {
        let error = generate(
            "interface Present {}",
            Path::new("fixture.d.ts"),
            &["Missing".to_string()],
            false,
        )
        .expect_err("missing interface must fail");

        assert!(error.to_string().contains("Missing"));
    }
}
