//! Emit browser HTML/CSS/JS from the same UI DSL pipeline as native/mobile.

use crate::codegen::find_workspace_root;
use crate::css_parser::Stylesheet;
use crate::parser::{AppTree, Node, NodeKind, SignalDecl, StyleDecl};
use crate::style_matcher;
use anyhow::Result;
use std::path::Path;
use w3cos_std::style::{SafeAreaEdge, Spacing};

pub fn write_web_project(tree: &AppTree, stylesheet: &Stylesheet, output_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(output_dir)?;
    if let Ok(root) = find_workspace_root() {
        let font_src = root.join("crates/w3cos-runtime/assets/CJK-Subset.ttf");
        if font_src.exists() {
            let fonts_dir = output_dir.join("fonts");
            std::fs::create_dir_all(&fonts_dir)?;
            std::fs::copy(&font_src, fonts_dir.join("CJK-Subset.ttf"))?;
        }
    }
    let signal_names: Vec<&str> = tree.signals.iter().map(|s| s.name.as_str()).collect();
    let body = gen_html_node(&tree.root, 0, &signal_names, stylesheet);
    let css = emit_stylesheet(stylesheet);
    let js = gen_runtime(&tree.signals, &signal_names);

    std::fs::write(
        output_dir.join("index.html"),
        format!(
            r#"<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover, interactive-widget=resizes-content" />
  <title>W3C OS — web emit</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div id="root">{body}</div>
  <script src="app.js"></script>
</body>
</html>
"#
        ),
    )?;
    std::fs::write(output_dir.join("styles.css"), css)?;
    std::fs::write(output_dir.join("app.js"), js)?;
    Ok(())
}

fn gen_runtime(signals: &[SignalDecl], names: &[&str]) -> String {
    let inits: Vec<String> = signals
        .iter()
        .map(|s| format!("  {}: {},", s.name, s.initial.js_initializer()))
        .collect();
    let index_map: Vec<String> = names
        .iter()
        .enumerate()
        .map(|(i, n)| format!("  {n}: {i},"))
        .collect();

    format!(
        r#"// Auto-generated by w3cos web_codegen — same TSX as native/mobile
const state = {{
{state_lines}
}};

const signalIndex = {{
{index_lines}
}};

function bindState() {{
  document.querySelectorAll('[data-bind]').forEach((el) => {{
    const key = el.dataset.bind;
    if (key in state) el.textContent = String(state[key]);
  }});
  document.querySelectorAll('[data-show]').forEach((el) => {{
    const [key, val] = el.dataset.show.split(':');
    el.style.display = state[key] == parseInt(val, 10) ? '' : 'none';
  }});
  document.querySelectorAll('[data-bg-signal]').forEach((el) => {{
    const [key, a, b] = el.dataset.bgSignal.split('|');
    el.style.backgroundColor = state[key] === 0 ? a : b;
  }});
  const panel = document.getElementById('anim-panel');
  if (panel) {{
    panel.style.opacity = String(state.animOpacity / 100);
    panel.style.backgroundColor = state.animBg === 0 ? '#1e293b' : '#7c3aed';
  }}
}}

function executeAction(action) {{
  if (!action) return;
  const parts = action.split(':');
  if (parts[0] === 'history') {{
    const op = parts[1];
    const routeKey = parts[2] || 'route';
    if (op === 'push') {{
      const value = parseInt(parts[3] || '0', 10);
      const path = parts.slice(4).join(':') || '/';
      state[routeKey] = value;
      history.pushState(String(value), '', path);
    }} else if (op === 'back') {{
      history.back();
      const restored = history.state != null ? parseInt(history.state, 10) : 0;
      state[routeKey] = Number.isFinite(restored) ? restored : 0;
    }}
    bindState();
    return;
  }}
  if (parts[0] === 'fetch' && parts.length >= 5) {{
    const statusKey = parts[2];
    const bytesKey = parts[3];
    const url = parts.slice(4).join(':');
    fetch(url).then(async (res) => {{
      const buf = await res.arrayBuffer();
      state[statusKey] = res.status;
      state[bytesKey] = buf.byteLength;
      bindState();
    }}).catch(() => {{
      state[statusKey] = 0;
      state[bytesKey] = -1;
      bindState();
    }});
    return;
  }}
  if (parts.length < 2) return;
  const op = parts[0];
  const key = parts[1];
  if (op === 'increment') state[key] = (state[key] || 0) + 1;
  else if (op === 'decrement') state[key] = (state[key] || 0) - 1;
  else if (op === 'set') state[key] = parseInt(parts[2] || '0', 10);
  else if (op === 'toggle') state[key] = state[key] === 0 ? 1 : 0;
  bindState();
}}

document.getElementById('root').addEventListener('click', (e) => {{
  const el = e.target.closest('[data-action]');
  if (el) executeAction(el.getAttribute('data-action'));
}});

bindState();

function syncKeyboardInset() {{
  const vv = window.visualViewport;
  if (!vv) {{
    document.documentElement.style.setProperty('--w3cos-keyboard-inset-height', '0px');
    return;
  }}
  const inset = Math.max(0, window.innerHeight - vv.height - vv.offsetTop);
  document.documentElement.style.setProperty('--w3cos-keyboard-inset-height', inset + 'px');
}}
if (window.visualViewport) {{
  window.visualViewport.addEventListener('resize', syncKeyboardInset);
  window.visualViewport.addEventListener('scroll', syncKeyboardInset);
}}
syncKeyboardInset();
"#,
        state_lines = inits.join("\n"),
        index_lines = index_map.join("\n"),
    )
}

fn gen_html_node(
    node: &Node,
    depth: usize,
    signal_names: &[&str],
    stylesheet: &Stylesheet,
) -> String {
    if let Some((sig, val)) = &node.show_when {
        let inner = if node.children.len() == 1 {
            gen_html_node(&node.children[0], depth + 1, signal_names, stylesheet)
        } else {
            node.children
                .iter()
                .map(|c| gen_html_node(c, depth + 1, signal_names, stylesheet))
                .collect::<String>()
        };
        return format!(r#"<div data-show="{sig}:{val}">{inner}</div>"#);
    }
    let resolved = style_matcher::resolve_style(node, stylesheet);
    let inline = style_decl_to_css(&resolved, signal_names);
    let class_attr = node
        .class_name
        .as_ref()
        .map(|c| format!(r#" class="{c}""#))
        .unwrap_or_default();
    let style_attr = if inline.is_empty() {
        String::new()
    } else {
        format!(r#" style="{inline}""#)
    };
    let action_attr = node
        .on_click
        .as_ref()
        .map(|a| format!(r#" data-action="{a}""#))
        .unwrap_or_default();

    match &node.kind {
        NodeKind::Text(content) => {
            let text = node.text.as_deref().unwrap_or(content.as_str());
            let inner = gen_text_html(text, signal_names);
            let text_style = if inline.is_empty() {
                r#" style="display:inline-block""#.to_string()
            } else if inline.contains("display:") {
                style_attr.clone()
            } else {
                format!(r#" style="display:inline-block;{inline}""#)
            };
            format!("<span{class_attr}{text_style}>{inner}</span>")
        }
        NodeKind::Button(label) => {
            let lbl = node.label.as_deref().unwrap_or(label.as_str());
            format!(
                "<button{type_hint}{class_attr}{style_attr}{action_attr}>{lbl}</button>",
                type_hint = r#" type="button""#
            )
        }
        NodeKind::Image(src) => {
            let src_val = node.src.as_deref().unwrap_or(src.as_str());
            format!(r#"<img src="{src_val}" alt=""{class_attr}{style_attr} />"#)
        }
        NodeKind::TextInput => {
            let ph = node.placeholder.as_deref().unwrap_or("Enter text");
            format!(r#"<input type="text" placeholder="{ph}"{class_attr}{style_attr} />"#)
        }
        NodeKind::Column | NodeKind::Row | NodeKind::Box => {
            let mut extra = String::new();
            if matches!(node.kind, NodeKind::Column) {
                extra.push_str("display:flex;flex-direction:column;");
            } else if matches!(node.kind, NodeKind::Row) {
                extra.push_str("display:flex;flex-direction:row;");
            }
            let id_attr = if resolved.opacity_from_signal.is_some()
                || resolved.background_from_signal.is_some()
            {
                " id=\"anim-panel\"".to_string()
            } else {
                String::new()
            };
            let style_attr = if extra.is_empty() && inline.is_empty() {
                style_attr.clone()
            } else {
                format!(
                    r#" style="{}{}""#,
                    extra,
                    if inline.is_empty() {
                        String::new()
                    } else {
                        inline.clone()
                    }
                )
            };
            let children: String = node
                .children
                .iter()
                .map(|c| gen_html_node(c, depth + 1, signal_names, stylesheet))
                .collect();
            format!("<div{id_attr}{class_attr}{style_attr}{action_attr}>{children}</div>")
        }
    }
}

fn gen_text_html(text: &str, signal_names: &[&str]) -> String {
    if !text.contains('{') {
        return escape_html(text);
    }
    let mut out = String::new();
    let mut rest = text;
    while let Some(start) = rest.find('{') {
        out.push_str(&escape_html(&rest[..start]));
        if let Some(end) = rest[start..].find('}') {
            let key = &rest[start + 1..start + end];
            if signal_names.contains(&key) {
                out.push_str(&format!(r#"<span data-bind="{key}"></span>"#));
            } else {
                out.push_str(&escape_html(&rest[start..=start + end]));
            }
            rest = &rest[start + end + 1..];
        } else {
            out.push_str(&escape_html(rest));
            return out;
        }
    }
    out.push_str(&escape_html(rest));
    out
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn emit_stylesheet(_sheet: &Stylesheet) -> String {
    String::from(
        r#"/* w3cos web emit — mobile shell + inline node styles */
@font-face{font-family:'W3cosUI';src:url('fonts/CJK-Subset.ttf') format('truetype');font-display:swap}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;padding:0;height:100%;background:#0b1220;font-family:'W3cosUI',-apple-system,BlinkMacSystemFont,system-ui,sans-serif;-webkit-font-smoothing:antialiased}
body{display:flex;justify-content:center;align-items:flex-start}
#root{width:402px;height:874px;max-height:100vh;display:flex;flex-direction:column;overflow:hidden;background:#f7f9fc}
.screen{flex:1;min-height:0;display:flex;flex-direction:column}
.feed{flex:1 1 0;min-height:0!important;height:auto!important;overflow:auto!important;-webkit-overflow-scrolling:touch}
.feed-content{flex-shrink:0}
button{border:none;cursor:pointer;font-family:inherit;background:transparent;line-height:1.2;min-height:0;padding:0;margin:0}
input{font-family:inherit;outline:none;width:100%;border:none}
img{display:block;max-width:100%}
[data-action]{cursor:pointer}
"#,
    )
}

fn style_decl_to_css(s: &StyleDecl, signal_names: &[&str]) -> String {
    let mut parts: Vec<String> = Vec::new();
    macro_rules! px {
        ($opt:expr, $prop:literal) => {
            if let Some(v) = $opt {
                parts.push(format!("{}:{}px", $prop, v));
            }
        };
    }
    px!(s.gap, "gap");
    if let Some(p) = padding_css(s) {
        parts.push(p);
    }
    if let Some(m) = s.margin {
        parts.push(format!("margin:{}", spacing_css(m)));
    }
    px!(s.font_size, "font-size");
    if let Some(w) = s.font_weight {
        parts.push(format!("font-weight:{w}"));
    }
    if let Some(c) = s.color.as_ref() {
        parts.push(format!("color:{c}"));
    }
    if let Some(bg) = s.background.as_ref() {
        parts.push(format!("background:{bg}"));
    }
    if let Some((sig, a, b)) = s.background_from_signal.as_ref() {
        if signal_names.contains(&sig.as_str()) {
            parts.push(format!("background:var(--bg-{sig},{a})"));
            let _ = b;
        }
    }
    px!(s.border_radius, "border-radius");
    px!(s.border_width, "border-width");
    if let Some(c) = s.border_color.as_ref() {
        parts.push(format!("border-color:{c}"));
        parts.push("border-style:solid".into());
    }
    if let Some(ai) = s.align_items.as_ref() {
        parts.push(format!("align-items:{}", css_flex_align(ai)));
    }
    if let Some(jc) = s.justify_content.as_ref() {
        parts.push(format!("justify-content:{}", css_flex_justify(jc)));
    }
    if let Some(display) = s.display.as_ref() {
        parts.push(format!("display:{display}"));
    }
    if let Some(direction) = s.flex_direction.as_ref() {
        parts.push(format!("flex-direction:{direction}"));
    }
    if let Some(fg) = s.flex_grow {
        parts.push(format!("flex-grow:{fg}"));
    }
    if let Some(fs) = s.flex_shrink {
        parts.push(format!("flex-shrink:{fs}"));
    }
    if let Some(fw) = s.flex_wrap.as_ref() {
        parts.push(format!("flex-wrap:{}", fw));
    }
    if let Some(fb) = s.flex_basis.as_ref() {
        parts.push(format!("flex-basis:{}", css_dim(fb)));
    }
    if let Some(w) = s.width.as_ref() {
        parts.push(format!("width:{}", css_dim(w)));
    }
    if let Some(h) = s.height.as_ref() {
        parts.push(format!("height:{}", css_dim(h)));
    }
    if let Some(mw) = s.min_width.as_ref() {
        parts.push(format!("min-width:{}", css_dim(mw)));
    }
    if let Some(mh) = s.min_height.as_ref() {
        parts.push(format!("min-height:{}", css_dim(mh)));
    }
    if let Some(mw) = s.max_width.as_ref() {
        parts.push(format!("max-width:{}", css_dim(mw)));
    }
    if let Some(mh) = s.max_height.as_ref() {
        parts.push(format!("max-height:{}", css_dim(mh)));
    }
    if let Some(position) = s.position.as_ref() {
        parts.push(format!("position:{position}"));
    }
    if let Some(top) = s.top.as_ref() {
        parts.push(format!("top:{}", css_dim(top)));
    }
    if let Some(right) = s.right.as_ref() {
        parts.push(format!("right:{}", css_dim(right)));
    }
    if let Some(bottom) = s.bottom.as_ref() {
        parts.push(format!("bottom:{}", css_dim(bottom)));
    }
    if let Some(left) = s.left.as_ref() {
        parts.push(format!("left:{}", css_dim(left)));
    }
    if let Some(z_index) = s.z_index {
        parts.push(format!("z-index:{z_index}"));
    }
    if let Some(lh) = s.line_height {
        parts.push(format!("line-height:{lh}"));
    }
    if let Some(ws) = s.white_space.as_ref() {
        let v = match ws.as_str() {
            "nowrap" | "noWrap" => "nowrap",
            "pre" => "pre",
            "pre-wrap" | "preWrap" => "pre-wrap",
            "pre-line" | "preLine" => "pre-line",
            _ => "normal",
        };
        parts.push(format!("white-space:{v}"));
    }
    if let Some(ov) = s.overflow.as_ref() {
        parts.push(format!("overflow:{ov}"));
    }
    if let Some(behavior) = s.overscroll_behavior.as_ref() {
        parts.push(format!("overscroll-behavior:{behavior}"));
    }
    if let Some(op) = s.opacity {
        parts.push(format!("opacity:{op}"));
    }
    if let Some(sig) = s.opacity_from_signal.as_ref() {
        if signal_names.contains(&sig.as_str()) {
            parts.push(format!("opacity:calc(var(--op-{sig},100)/100)"));
        }
    }
    if let Some(tr) = s.transition.as_ref() {
        parts.push(format!("transition:{tr}"));
    }
    if let Some(shadow) = s.box_shadow.as_ref() {
        parts.push(format!("box-shadow:{shadow}"));
    }
    if let Some(ta) = s.text_align.as_ref() {
        parts.push(format!("text-align:{ta}"));
    }
    if let Some(spacing) = s.letter_spacing {
        parts.push(format!("letter-spacing:{spacing}px"));
    }
    parts.join(";")
}

fn spacing_css(s: Spacing) -> String {
    const KB_ENV: &str = "env(keyboard-inset-height, var(--w3cos-keyboard-inset-height, 0px))";
    match s {
        Spacing::Px(v) => format!("{v}px"),
        Spacing::SafeAreaInset(SafeAreaEdge::Top) => "env(safe-area-inset-top)".to_string(),
        Spacing::SafeAreaInset(SafeAreaEdge::Right) => "env(safe-area-inset-right)".to_string(),
        Spacing::SafeAreaInset(SafeAreaEdge::Bottom) => "env(safe-area-inset-bottom)".to_string(),
        Spacing::SafeAreaInset(SafeAreaEdge::Left) => "env(safe-area-inset-left)".to_string(),
        Spacing::KeyboardInsetHeight => KB_ENV.to_string(),
        Spacing::Composite {
            px,
            safe_area,
            keyboard_inset,
        } => {
            let mut terms: Vec<String> = Vec::new();
            if px.abs() > f32::EPSILON {
                terms.push(format!("{px}px"));
            }
            if let Some(e) = safe_area {
                terms.push(match e {
                    SafeAreaEdge::Top => "env(safe-area-inset-top)".to_string(),
                    SafeAreaEdge::Right => "env(safe-area-inset-right)".to_string(),
                    SafeAreaEdge::Bottom => "env(safe-area-inset-bottom)".to_string(),
                    SafeAreaEdge::Left => "env(safe-area-inset-left)".to_string(),
                });
            }
            if keyboard_inset {
                terms.push(KB_ENV.to_string());
            }
            match terms.len() {
                0 => "0px".to_string(),
                1 => terms[0].clone(),
                _ => format!("calc({})", terms.join(" + ")),
            }
        }
    }
}

fn padding_css(s: &StyleDecl) -> Option<String> {
    let (t, r, b, l) = if s.padding_top.is_some()
        || s.padding_right.is_some()
        || s.padding_bottom.is_some()
        || s.padding_left.is_some()
    {
        let fallback = s.padding.unwrap_or(Spacing::Px(0.0));
        (
            s.padding_top.unwrap_or(fallback),
            s.padding_right.unwrap_or(fallback),
            s.padding_bottom.unwrap_or(fallback),
            s.padding_left.unwrap_or(fallback),
        )
    } else if let Some(p) = s.padding {
        (p, p, p, p)
    } else {
        return None;
    };
    if t == r && r == b && b == l {
        Some(format!("padding:{}", spacing_css(t)))
    } else if t == b && r == l {
        Some(format!("padding:{} {}", spacing_css(t), spacing_css(r)))
    } else {
        Some(format!(
            "padding:{} {} {} {}",
            spacing_css(t),
            spacing_css(r),
            spacing_css(b),
            spacing_css(l)
        ))
    }
}

fn css_dim(v: &str) -> String {
    let v = v.trim();
    if v.ends_with("px") || v.ends_with('%') {
        v.to_string()
    } else {
        format!("{v}px")
    }
}

fn css_flex_align(v: &str) -> &str {
    match v {
        "center" => "center",
        "flex-start" | "flexStart" => "flex-start",
        "flex-end" | "flexEnd" => "flex-end",
        "baseline" => "baseline",
        _ => "stretch",
    }
}

fn css_flex_justify(v: &str) -> &str {
    match v {
        "center" => "center",
        "flex-end" | "flexEnd" => "flex-end",
        "space-between" | "spaceBetween" => "space-between",
        "space-around" | "spaceAround" => "space-around",
        "space-evenly" | "spaceEvenly" => "space-evenly",
        _ => "flex-start",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::css_parser::Stylesheet;
    use crate::parser::parse;

    #[test]
    fn web_emit_smoke() {
        let src = r#"import { Column, Text, Button } from "@w3cos/std"
const count = signal(0)
export default
<Column style={{ gap: 8, padding: 16 }}>
  <Text>{count}</Text>
  <Button onClick="increment:count">+</Button>
</Column>"#;
        let tree = parse(src).expect("parse");
        let dir = tempfile::tempdir().unwrap();
        write_web_project(&tree, &Stylesheet::empty(), dir.path()).expect("write");
        let html = std::fs::read_to_string(dir.path().join("index.html")).unwrap();
        assert!(html.contains("data-bind=\"count\""));
        assert!(html.contains("data-action=\"increment:count\""));
    }
}
