//! Auto-generated by w3cos compiler — do not edit.
use w3cos_std::{Component, Style};
use w3cos_std::style::*;
use w3cos_std::color::Color;

fn main() {
    w3cos_runtime::run_app(build_ui).expect("W3C OS app crashed");
}

fn build_ui() -> Component {
    Component::column(Style {
        gap: 0_f32,
        background: Color::from_hex("#0a0a12"),
        ..Style::default()
    }, vec![
            Component::row(Style {
                padding: Edges::all(16_f32),
                background: Color::from_hex("#12121f"),
                align_items: AlignItems::Center,
                justify_content: JustifyContent::SpaceBetween,
                ..Style::default()
            }, vec![
                    Component::row(Style {
                        gap: 10_f32,
                        align_items: AlignItems::Center,
                        ..Style::default()
                    }, vec![
                            Component::text("◆", Style {
                                font_size: 22_f32,
                                color: Color::from_hex("#6c5ce7"),
                                ..Style::default()
                            }),
                            Component::text("W3C OS", Style {
                                font_size: 18_f32,
                                font_weight: 700,
                                color: Color::from_hex("#dfe6e9"),
                                ..Style::default()
                            }),
                    ]),
                    Component::row(Style {
                        gap: 20_f32,
                        align_items: AlignItems::Center,
                        ..Style::default()
                    }, vec![
                            Component::text("Dashboard", Style {
                                font_size: 14_f32,
                                color: Color::from_hex("#a0a0c0"),
                                ..Style::default()
                            }),
                            Component::text("Apps", Style {
                                font_size: 14_f32,
                                color: Color::from_hex("#a0a0c0"),
                                ..Style::default()
                            }),
                            Component::text("Settings", Style {
                                font_size: 14_f32,
                                color: Color::from_hex("#a0a0c0"),
                                ..Style::default()
                            }),
                    ]),
            ]),
            Component::row(Style {
                gap: 0_f32,
                flex_grow: 1_f32,
                ..Style::default()
            }, vec![
                    Component::column(Style {
                        gap: 4_f32,
                        padding: Edges::all(20_f32),
                        background: Color::from_hex("#10101c"),
                        width: Dimension::Px(220_f32),
                        ..Style::default()
                    }, vec![
                            Component::text("NAVIGATION", Style {
                                font_size: 11_f32,
                                font_weight: 700,
                                color: Color::from_hex("#505070"),
                                ..Style::default()
                            }),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                background: Color::from_hex("#6c5ce7"),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("⬡", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#ffffff"),
                                        ..Style::default()
                                    }),
                                    Component::text("Overview", Style {
                                        font_size: 14_f32,
                                        font_weight: 600,
                                        color: Color::from_hex("#ffffff"),
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("◈", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#606080"),
                                        ..Style::default()
                                    }),
                                    Component::text("Applications", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#a0a0c0"),
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("◉", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#606080"),
                                        ..Style::default()
                                    }),
                                    Component::text("Processes", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#a0a0c0"),
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("⬢", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#606080"),
                                        ..Style::default()
                                    }),
                                    Component::text("File System", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#a0a0c0"),
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("◎", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#606080"),
                                        ..Style::default()
                                    }),
                                    Component::text("Network", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#a0a0c0"),
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 8_f32,
                                padding: Edges::all(10_f32),
                                border_radius: 8_f32,
                                align_items: AlignItems::Center,
                                ..Style::default()
                            }, vec![
                                    Component::text("⚙", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#606080"),
                                        ..Style::default()
                                    }),
                                    Component::text("AI Agents", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#a0a0c0"),
                                        ..Style::default()
                                    }),
                            ]),
                    ]),
                    Component::column(Style {
                        gap: 20_f32,
                        padding: Edges::all(24_f32),
                        flex_grow: 1_f32,
                        ..Style::default()
                    }, vec![
                            Component::row(Style {
                                align_items: AlignItems::Center,
                                justify_content: JustifyContent::SpaceBetween,
                                ..Style::default()
                            }, vec![
                                    Component::column(Style {
                                        gap: 4_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::text("System Overview", Style {
                                                font_size: 24_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::text("All systems operational", Style {
                                                font_size: 14_f32,
                                                color: Color::from_hex("#00b894"),
                                                ..Style::default()
                                            }),
                                    ]),
                                    Component::button("New App", Style {
                                        font_size: 14_f32,
                                        color: Color::from_hex("#ffffff"),
                                        background: Color::from_hex("#6c5ce7"),
                                        border_radius: 8_f32,
                                        ..Style::default()
                                    }),
                            ]),
                            Component::row(Style {
                                gap: 16_f32,
                                ..Style::default()
                            }, vec![
                                    Component::column(Style {
                                        gap: 8_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 1_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::row(Style {
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::text("CPU", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#8080a0"),
                                                        ..Style::default()
                                                    }),
                                                    Component::text("23%", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#00b894"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::text("1.2 GHz", Style {
                                                font_size: 28_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::row(Style {
                                                background: Color::from_hex("#1e1e38"),
                                                border_radius: 3_f32,
                                                height: Dimension::Px(6_f32),
                                                ..Style::default()
                                            }, vec![
                                                    Component::column(Style {
                                                        background: Color::from_hex("#00b894"),
                                                        border_radius: 3_f32,
                                                        width: Dimension::Percent(23_f32),
                                                        height: Dimension::Px(6_f32),
                                                        ..Style::default()
                                                    }, vec![]),
                                            ]),
                                    ]),
                                    Component::column(Style {
                                        gap: 8_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 1_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::row(Style {
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::text("Memory", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#8080a0"),
                                                        ..Style::default()
                                                    }),
                                                    Component::text("67%", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#fdcb6e"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::text("5.4 / 8 GB", Style {
                                                font_size: 28_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::row(Style {
                                                background: Color::from_hex("#1e1e38"),
                                                border_radius: 3_f32,
                                                height: Dimension::Px(6_f32),
                                                ..Style::default()
                                            }, vec![
                                                    Component::column(Style {
                                                        background: Color::from_hex("#fdcb6e"),
                                                        border_radius: 3_f32,
                                                        width: Dimension::Percent(67_f32),
                                                        height: Dimension::Px(6_f32),
                                                        ..Style::default()
                                                    }, vec![]),
                                            ]),
                                    ]),
                                    Component::column(Style {
                                        gap: 8_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 1_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::row(Style {
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::text("Storage", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#8080a0"),
                                                        ..Style::default()
                                                    }),
                                                    Component::text("41%", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#74b9ff"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::text("205 / 512 GB", Style {
                                                font_size: 28_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::row(Style {
                                                background: Color::from_hex("#1e1e38"),
                                                border_radius: 3_f32,
                                                height: Dimension::Px(6_f32),
                                                ..Style::default()
                                            }, vec![
                                                    Component::column(Style {
                                                        background: Color::from_hex("#74b9ff"),
                                                        border_radius: 3_f32,
                                                        width: Dimension::Percent(41_f32),
                                                        height: Dimension::Px(6_f32),
                                                        ..Style::default()
                                                    }, vec![]),
                                            ]),
                                    ]),
                                    Component::column(Style {
                                        gap: 8_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 1_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::row(Style {
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::text("Network", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#8080a0"),
                                                        ..Style::default()
                                                    }),
                                                    Component::text("↑↓", Style {
                                                        font_size: 13_f32,
                                                        color: Color::from_hex("#a29bfe"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::text("84 Mbps", Style {
                                                font_size: 28_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::text("12ms latency", Style {
                                                font_size: 13_f32,
                                                color: Color::from_hex("#606080"),
                                                ..Style::default()
                                            }),
                                    ]),
                            ]),
                            Component::row(Style {
                                gap: 16_f32,
                                flex_grow: 1_f32,
                                ..Style::default()
                            }, vec![
                                    Component::column(Style {
                                        gap: 12_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 2_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::text("Running Applications", Style {
                                                font_size: 16_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::row(Style {
                                                padding: Edges::all(12_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        gap: 10_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("◆", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#6c5ce7"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("file-manager.w3c", Style {
                                                                font_size: 14_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::row(Style {
                                                        gap: 16_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("24 MB", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#8080a0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("2%", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#00b894"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("PID 1024", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#606080"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                            ]),
                                            Component::row(Style {
                                                padding: Edges::all(12_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        gap: 10_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("◆", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#00b894"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("terminal.w3c", Style {
                                                                font_size: 14_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::row(Style {
                                                        gap: 16_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("18 MB", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#8080a0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("1%", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#00b894"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("PID 1025", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#606080"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                            ]),
                                            Component::row(Style {
                                                padding: Edges::all(12_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                align_items: AlignItems::Center,
                                                justify_content: JustifyContent::SpaceBetween,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        gap: 10_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("◆", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#fdcb6e"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("ai-agent-hub.w3c", Style {
                                                                font_size: 14_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::row(Style {
                                                        gap: 16_f32,
                                                        align_items: AlignItems::Center,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("156 MB", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#8080a0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("15%", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#fdcb6e"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("PID 1026", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#606080"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                            ]),
                                    ]),
                                    Component::column(Style {
                                        gap: 12_f32,
                                        padding: Edges::all(20_f32),
                                        background: Color::from_hex("#16162a"),
                                        border_radius: 12_f32,
                                        flex_grow: 1_f32,
                                        ..Style::default()
                                    }, vec![
                                            Component::text("AI Agent Status", Style {
                                                font_size: 16_f32,
                                                font_weight: 700,
                                                color: Color::from_hex("#f0f0ff"),
                                                ..Style::default()
                                            }),
                                            Component::column(Style {
                                                gap: 6_f32,
                                                padding: Edges::all(14_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        justify_content: JustifyContent::SpaceBetween,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("Code Agent", Style {
                                                                font_size: 13_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("Active", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#00b894"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::text("Building filesystem module...", Style {
                                                        font_size: 12_f32,
                                                        color: Color::from_hex("#606080"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::column(Style {
                                                gap: 6_f32,
                                                padding: Edges::all(14_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        justify_content: JustifyContent::SpaceBetween,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("Review Agent", Style {
                                                                font_size: 13_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("Idle", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#8080a0"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::text("Waiting for PR #42", Style {
                                                        font_size: 12_f32,
                                                        color: Color::from_hex("#606080"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                            Component::column(Style {
                                                gap: 6_f32,
                                                padding: Edges::all(14_f32),
                                                background: Color::from_hex("#1c1c34"),
                                                border_radius: 8_f32,
                                                ..Style::default()
                                            }, vec![
                                                    Component::row(Style {
                                                        justify_content: JustifyContent::SpaceBetween,
                                                        ..Style::default()
                                                    }, vec![
                                                            Component::text("Test Agent", Style {
                                                                font_size: 13_f32,
                                                                color: Color::from_hex("#d0d0e0"),
                                                                ..Style::default()
                                                            }),
                                                            Component::text("Running", Style {
                                                                font_size: 12_f32,
                                                                color: Color::from_hex("#fdcb6e"),
                                                                ..Style::default()
                                                            }),
                                                    ]),
                                                    Component::text("47/52 tests passed", Style {
                                                        font_size: 12_f32,
                                                        color: Color::from_hex("#606080"),
                                                        ..Style::default()
                                                    }),
                                            ]),
                                    ]),
                            ]),
                    ]),
            ]),
    ])
}
